# Data Validation & Cleaning

### Importing pandas and load cvs file

In [2]:
import pandas as pd 

games = pd.read_csv('mobile_game_inapp_purchases.csv')

games

,UserID,Age,Gender,Country,Device,GameGenre,SessionCount,AverageSessionLength,SpendingSegment,InAppPurchaseAmount,FirstPurchaseDaysAfterInstall,PaymentMethod,LastPurchaseDate
0,c9889ab0-9cfc-4a75-acd9-5eab1df0015c,49.0,Male,Norway,Android,Battle Royale,9,12.83,Minnow,11.40,28.0,Apple Pay,2025-03-19
1,7c9e413c-ecca-45f2-a780-2826a07952a2,15.0,Male,Switzerland,iOS,Action RPG,11,19.39,Minnow,6.37,18.0,Debit Card,2025-06-08
2,fd61e419-1a92-4f43-a8c7-135842ad328a,23.0,Male,China,Android,Fighting,9,8.87,Minnow,15.81,30.0,Apple Pay,2025-06-02
3,bdb7f6d1-ff9a-468c-afe7-43f32a94293e,31.0,Male,Mexico,Android,Racing,12,19.56,Minnow,13.49,9.0,Debit Card,2025-04-01
4,aa7eec14-4846-47b9-b879-9c98038cda04,37.0,Female,India,Android,Battle Royale,10,15.23,Minnow,10.86,15.0,Paypal,2025-05-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,29f9fea9-591d-4e9f-a662-958655d3eb4a,19.0,Female,Iran,Android,Fighting,7,34.81,Minnow,12.48,16.0,Google Pay,2025-05-28
3020,c906eb00-fb33-4bf2-97a4-311634cd0d7a,48.0,Male,Switzerland,iOS,Adventure,9,19.45,Minnow,14.77,14.0,Carrier Billing,2025-07-25
3021,26e17717-ebec-42a9-aae2-2eff66888119,44.0,Male,France,Android,Card,15,20.54,Minnow,16.69,24.0,Gift Card,2025-01-25
3022,4d6e2bfb-cb11-411a-942c-4fb7a4832088,45.0,Male,Sweden,iOS,Fighting,8,14.48,Minnow,17.29,15.0,Paypal,2025-05-07
3023,37935b2e-9b5d-4a30-bf0f-751d105e31e3,22.0,Male,Egypt,Android,Adventure,10,28.54,Minnow,4.11,30.0,Carrier Billing,2025-07-06

### Counting NaNs

In [3]:
games.isna().sum()

UserID                             0
Age                               60
Gender                            60
Country                           60
Device                            60
GameGenre                         60
SessionCount                       0
AverageSessionLength               0
SpendingSegment                    0
InAppPurchaseAmount              136
FirstPurchaseDaysAfterInstall    136
PaymentMethod                    136
LastPurchaseDate                 136
dtype: int64

136 player records contain missing values across all purchase-related fields (InAppPurchaseAmount, PaymentMethod, FirstPurchaseDaysAfterInstall and LastPurchaseDate), while still being assigned a SpendingSegment.

Since the purchase information cannot be verified, these records will be excluded from analyses involving revenue and monetization metrics.

They were retained for gameplay and engagement analyses, as gameplay-related fields (SessionCount and AverageSessionLength) remain complete.

In [5]:
pd.set_option('display.max_rows', None)

games[
(games['SpendingSegment'].isin(['Whale', 'Minnow', 'Dolphin'])) &
(games['InAppPurchaseAmount'].isna())]

,UserID,Age,Gender,Country,Device,GameGenre,SessionCount,AverageSessionLength,SpendingSegment,InAppPurchaseAmount,FirstPurchaseDaysAfterInstall,PaymentMethod,LastPurchaseDate
11,a516f724-6b0f-438c-b20b-59f5f35ab06a,31.0,Male,Sweden,Android,Simulation,10,31.10,Dolphin,NaN,NaN,NaN,NaN
31,2868c7dc-a4bc-4143-8256-334e29ec7458,54.0,Female,USA,Android,Sandbox,13,21.86,Minnow,NaN,NaN,NaN,NaN
43,daa87ce2-9524-437b-96f5-d862e44ba2a6,20.0,Female,Egypt,iOS,Adventure,12,13.56,Minnow,NaN,NaN,NaN,NaN
50,9c3598c6-6cd4-4da2-81ed-a8053987aa80,33.0,Female,Japan,Android,Fighting,12,26.08,Minnow,NaN,NaN,NaN,NaN
78,d88da455-eacb-4fc0-b7d8-9ee22f1c0ffa,18.0,Male,Saudi Arabia,Android,Fighting,6,34.42,Minnow,NaN,NaN,NaN,NaN
81,55b14ef0-9383-48b5-9e88-b5814331b23d,NaN,Female,UK,iOS,Puzzle,12,24.44,Minnow,NaN,NaN,NaN,NaN
113,ea67c7b3-f672-4d1f-a87c-b6ad687805d7,52.0,Male,Mexico,iOS,MOBA,13,12.44,Minnow,NaN,NaN,NaN,NaN
117,d4cb7f92-952d-4528-b4bb-96d4a9bd038a,37.0,Male,Italy,NaN,Strategy,9,8.16,Minnow,NaN,NaN,NaN,NaN
122,1f582143-b515-493b-86c9-8a36fedffabe,25.0,Female,USA,Android,Puzzle,9,22.35,Minnow,NaN,NaN,NaN,NaN
124,f952dd17-61b1-4f47-a01f-19e66d0b84dc,40.0,Female,Sweden,iOS,Fighting,10,25.38,Dolphin,NaN,NaN,NaN,NaN
132,c97c7aeb-5d60-4f9c-9e55-cdce38c7e8e1,43.0,Male,Mexico,iOS,Racing,8,22.52,Minnow,NaN,NaN,NaN,NaN
188,bd726fee-fde2-4063-8532-3f16aa8e2a56,NaN,Male,Afghanistan,iOS,Adventure,15,34.45,Dolphin,NaN,NaN,NaN,NaN
192,8dd3d210-13f7-4ec2-a2d7-924d7d3a1dd1,35.0,NaN,South Korea,Android,Fighting,6,26.24,Minnow,NaN,NaN,NaN,NaN
254,1bf14ea6-aab2-4d68-be04-832f9515b183,49.0,Female,Australia,iOS,Simulation,9,25.41,Minnow,NaN,NaN,NaN,NaN
280,7bc343df-adbc-461f-bc81-b65479e84dff,22.0,Female,USA,Android,Battle Royale,8,27.75,Minnow,NaN,NaN,NaN,NaN
288,4567b4e7-63c4-438c-98d9-090299bb2fbf,51.0,Male,Sweden,Android,NaN,11,26.76,Minnow,NaN,NaN,NaN,NaN
295,54ad687f-2f78-4f4d-a133-ce5f72251f46,48.0,Female,Brazil,Android,Card,11,12.78,Minnow,NaN,NaN,NaN,NaN
363,539959df-ef71-49f6-97a0-f7d6262a7dc7,24.0,Other,Australia,Android,NaN,4,6.42,Minnow,NaN,NaN,NaN,NaN
366,4c8dc359-6da5-4d57-9361-fc07378babed,22.0,Male,Norway,NaN,Sports,10,10.37,Minnow,NaN,NaN,NaN,NaN
382,62962e36-3080-4054-a7a6-5b34c8d5dac3,35.0,Male,Sweden,iOS,Strategy,14,11.78,Minnow,NaN,NaN,NaN,NaN
406,91e70ebc-347e-4009-9313-5441a781d64f,18.0,Male,Germany,Android,Sandbox,8,14.49,Minnow,NaN,NaN,NaN,NaN
411,f832f6a5-b543-41ca-9d6e-b797e7347af0,32.0,Female,Switzerland,iOS,Battle Royale,9,30.67,Minnow,NaN,NaN,NaN,NaN
426,81fe2e28-147d-4167-8bd7-47fd7015a9ea,29.0,Female,Australia,iOS,Puzzle,8,17.77,Minnow,NaN,NaN,NaN,NaN
438,709fa97d-f855-422f-a5bc-8968f4e19cc3,24.0,Female,Saudi Arabia,iOS,Strategy,10,17.93,Dolphin,NaN,NaN,NaN,NaN
450,8f5ccb0c-6793-47da-8822-ddf479d26655,NaN,Female,China,Android,Role Playing,9,12.36,Minnow,NaN,NaN,NaN,NaN
456,c9fdc365-34cf-4e37-be13-fc0f2d376aef,52.0,Male,Canada,Android,MMORPG,12,28.91,Minnow,NaN,NaN,NaN,NaN
462,fc152543-3853-42ee-838b-13105398b12a,52.0,Male,Sweden,Android,MMORPG,8,33.53,Minnow,NaN,NaN,NaN,NaN
465,726b8b30-2a12-4bf2-b9c8-8891cbc23a6b,54.0,Female,Japan,iOS,Puzzle,12,27.72,Minnow,NaN,NaN,NaN,NaN
485,3e234cc5-e1d5-485e-95a1-00e920b8bb68,52.0,Male,Brazil,NaN,MMORPG,14,15.44,Minnow,NaN,NaN,NaN,NaN
491,797e1746-24b0-47c3-8f1c-794a1b4a2ce6,14.0,Male,Saudi Arabia,Android,Puzzle,10,6.03,Minnow,NaN,NaN,NaN,NaN
498,9a1482c2-db2c-4e2d-a85a-7b49442204f7,52.0,Female,Sri Lanka,iOS,Fighting,6,32.25,Minnow,NaN,NaN,NaN,NaN
537,66a3f7e3-1f61-4498-b5d9-e9e87272cc39,14.0,Female,Turkey,Android,Racing,13,14.63,Minnow,NaN,NaN,NaN,NaN
552,fbf84fea-3218-430f-a826-19a408240de1,47.0,Male,USA,Android,Racing,7,13.58,Minnow,NaN,NaN,NaN,NaN
584,d9f8fc29-0e27-4dde-be38-75abf516c90f,17.0,Male,Bangladesh,iOS,Adventure,9,30.56,Minnow,NaN,NaN,NaN,NaN
595,77cfbcd8-e24e-40e0-87e6-6454e332ced8,54.0,Female,Russia,iOS,Action RPG,14,31.75,Minnow,NaN,NaN,NaN,NaN
614,330fc9fc-14b1-4091-82ae-551a3959cc13,46.0,Male,Canada,iOS,Battle Royale,10,24.35,Minnow,NaN,NaN,NaN,NaN
647,f37aae32-1dc0-42e8-8cb8-33b7fa6dcbf1,17.0,Male,Turkey,NaN,Card,11,29.20,Minnow,NaN,NaN,NaN,NaN
654,86d7b643-e17a-4f65-b4f9-9458e3a230b4,24.0,Male,India,iOS,Strategy,12,12.75,Minnow,NaN,NaN,NaN,NaN
700,cd2f9bac-ccf3-44e2-9907-920f2aca1acf,36.0,Female,Norway,Android,Card,12,7.65,Minnow,NaN,NaN,NaN,NaN
705,8653f820-a10f-49a8-9d39-75b837609778,NaN,Female,Russia,Android,Casual,12,30.12,Whale,NaN,NaN,NaN,NaN
721,74ace151-c3c0-4108-82fe-149265f941da,39.0,Female,Canada,iOS,MMORPG,14,16.73,Minnow,NaN,NaN,NaN,NaN
793,f7c1e895-b58e-456a-baf1-1c2172a911c9,42.0,Male,China,Android,Sports,8,26.29,Minnow,NaN,NaN,NaN,NaN
809,1388be92-1c61-4b8b-b11e-c2a72d22f573,13.0,Female,Turkey,Android,Casual,13,8.88,Minnow,NaN,NaN,NaN,NaN
823,102b9a6a-3652-4287-b11c-b15c6020fc8d,52.0,Male,Iran,Android,Racing,13,5.52,Whale,NaN,NaN,NaN,NaN
830,e0432954-fc8b-49ba-8ec8-3aee848cfba2,35.0,Female,Bangladesh,Android,Sports,9,26.26,Minnow,NaN,NaN,NaN,NaN
840,a0e120a9-34ff-4b7b-9063-0ca54abdc30b,23.0,Female,Sweden,iOS,Role Playing,10,25.97,Minnow,NaN,NaN,NaN,NaN
852,75ee7014-df8c-40da-8c80-8e73cfa5cedf,36.0,Female,Switzerland,Android,Racing,9,6.25,Minnow,NaN,NaN,NaN,NaN
871,f121ad44-3a36-47fa-9da3-da8b3d143578,32.0,Male,Afghanistan,Android,Casual,9,24.84,Minnow,NaN,NaN,NaN,NaN
899,e1a92218-67d4-4ab7-8d6b-7162b9f85f73,47.0,Male,India,Android,Racing,8,24.17,Minnow,NaN,NaN,NaN,NaN
902,b73b02dd-e65e-41b3-b0a0-33ef1d814c49,42.0,Male,Egypt,Android,Puzzle,8,8.85,Dolphin,NaN,NaN,NaN,NaN
919,971f2260-18a7-43d0-8d3e-d006b51d4e92,NaN,Female,India,iOS,Action RPG,14,5.26,Minnow,NaN,NaN,NaN,NaN
931,a62f9a4b-fc6b-44f8-8749-ad8dbb0434b6,22.0,Male,India,Android,MOBA,13,11.37,Minnow,NaN,NaN,NaN,NaN
944,fabdb396-84ba-4713-9edb-4c3db879c410,47.0,Male,Italy,Android,Simulation,6,6.85,Dolphin,NaN,NaN,NaN,NaN
946,bb8fc033-0ac7-40f2-ad34-7bc708dc2b1d,36.0,Female,Italy,Android,Sandbox,11,18.59,Minnow,NaN,NaN,NaN,NaN
951,f4f3f878-e165-497e-a37c-a238393fa267,22.0,Male,France,iOS,Role Playing,7,13.64,Minnow,NaN,NaN,NaN,NaN
1079,0469c44b-2010-4efb-94e2-1d14a330b3e5,33.0,Female,Germany,Android,Simulation,11,5.57,Minnow,NaN,NaN,NaN,NaN
1095,6eaa8137-17bf-47dc-bbab-6ed8e8434a13,30.0,Male,Sri Lanka,iOS,Adventure,3,25.96,Minnow,NaN,NaN,NaN,NaN
1230,e58ce150-764c-4168-b6e6-b1d13d0b814d,24.0,Female,France,Android,Strategy,9,26.35,Minnow,NaN,NaN,NaN,NaN
1236,67ee8e54-5ba6-4671-84c9-500bdfc945f4,28.0,Female,Turkey,iOS,MOBA,6,27.36,Dolphin,NaN,NaN,NaN,NaN
1243,04a2d312-f6eb-4e6c-bd84-4a084a4adec8,47.0,Male,India,iOS,Battle Royale,7,11.47,Minnow,NaN,NaN,NaN,NaN
1264,f4063506-bc02-49ec-9d3b-f1e7f580e5f2,40.0,Female,USA,iOS,Strategy,17,12.78,Minnow,NaN,NaN,NaN,NaN
1275,6ecc4256-a30d-460f-a704-4bd107d67055,14.0,Female,India,Android,Fighting,9,6.74,Minnow,NaN,NaN,NaN,NaN
1282,dcd571b1-f482-4f98-b891-29e6766432bf,44.0,Male,Mexico,iOS,Simulation,15,17.36,Minnow,NaN,NaN,NaN,NaN
1317,942e939f-52bf-49b6-8011-a5b9b2d395bd,51.0,Female,UK,iOS,Fighting,10,19.05,Minnow,NaN,NaN,NaN,NaN
1319,4660998a-6aa7-4b89-aab8-3b9a515090ac,42.0,Male,Iran,Android,Sandbox,11,13.19,Dolphin,NaN,NaN,NaN,NaN
1325,0994b7a2-46d5-4308-baf9-24118831b558,52.0,Female,South Korea,Android,Sports,8,7.14,Minnow,NaN,NaN,NaN,NaN
1596,9868c458-eaed-47ba-83e9-4e4db2b12021,33.0,Female,Japan,iOS,Battle Royale,9,11.20,Minnow,NaN,NaN,NaN,NaN
1607,3ee08ec5-bb9b-4ca4-9d8e-0411790474cb,16.0,Male,Denmark,iOS,Battle Royale,8,27.59,Minnow,NaN,NaN,NaN,NaN
1618,2cb3b1b3-eb76-4e18-98f8-5b9590377bca,35.0,Female,China,Android,MMORPG,8,23.64,Minnow,NaN,NaN,NaN,NaN
1639,308c9857-b40c-4c6c-8453-ab20e3cd5980,50.0,Male,Denmark,iOS,Casual,6,26.12,Minnow,NaN,NaN,NaN,NaN
1657,741d4974-0211-4532-a168-e6885ae06d79,32.0,Male,Turkey,iOS,Puzzle,11,20.32,Minnow,NaN,NaN,NaN,NaN
1671,34f0c917-4aae-4f09-8c58-36847e4dd8a3,24.0,Male,Denmark,iOS,Casual,11,16.70,Minnow,NaN,NaN,NaN,NaN
1683,7d8c4ea3-b9f8-489a-a3fb-291b026e145f,46.0,Male,Egypt,Android,Puzzle,11,7.05,Minnow,NaN,NaN,NaN,NaN
1707,2bcf70c9-62d9-44ec-a574-61b74842034a,NaN,Male,Switzerland,iOS,Adventure,14,24.70,Minnow,NaN,NaN,NaN,NaN
1741,24685113-1c81-4ef1-8b5f-9086c18ef8f4,30.0,Male,Spain,iOS,Fighting,15,23.00,Minnow,NaN,NaN,NaN,NaN
1764,a8a3ca0b-579a-47d0-b19e-17ed7aa4be8e,23.0,Female,USA,Android,Sandbox,11,23.83,Minnow,NaN,NaN,NaN,NaN
1796,d194658d-b22a-40ef-bec0-b6bf355baa7c,23.0,Male,Sweden,Android,Sports,13,21.60,Dolphin,NaN,NaN,NaN,NaN
1811,cec9f28d-4a9a-4fd6-9992-b5a46dba0773,26.0,Male,Saudi Arabia,Android,Racing,14,14.46,Minnow,NaN,NaN,NaN,NaN
1821,a41dc30d-c4ff-4ea2-a851-e3e7e9fab1b9,30.0,Female,France,iOS,Racing,6,18.69,Dolphin,NaN,NaN,NaN,NaN
1843,e635a5f2-efd2-46d0-bac4-4d294caebdf9,47.0,Female,China,Android,Simulation,7,15.71,Minnow,NaN,NaN,NaN,NaN
1855,629ffc86-3427-49db-97f7-b787eb40de39,31.0,Female,Canada,iOS,NaN,10,13.60,Minnow,NaN,NaN,NaN,NaN
1887,2f80fd04-ecc1-4a78-99f3-4e41d26db2a2,34.0,Female,Italy,Android,Role Playing,11,22.74,Dolphin,NaN,NaN,NaN,NaN
1893,ee71d160-5a9d-41ea-9ca4-79fa93d135e2,25.0,Male,India,Android,Action RPG,5,6.79,Minnow,NaN,NaN,NaN,NaN
1910,059bf54e-c933-400d-87d0-2eac7b00b051,27.0,Male,Netherlands,Android,MOBA,15,13.04,Dolphin,NaN,NaN,NaN,NaN
1980,465bafa5-5582-4764-b7a6-4551ed7e2508,26.0,Female,Canada,iOS,Adventure,12,30.23,Minnow,NaN,NaN,NaN,NaN
1988,2ccb05c5-4830-474e-8d68-48724384617b,16.0,Male,China,iOS,Sandbox,10,14.63,Minnow,NaN,NaN,NaN,NaN
2014,e30b291f-8252-4b78-9a5f-15b7c2fd9ba4,32.0,Male,Sweden,Android,Racing,8,15.89,Minnow,NaN,NaN,NaN,NaN
2040,518d747f-086c-4557-9791-ebf92bf89990,49.0,Male,Saudi Arabia,Android,Sandbox,11,16.35,Minnow,NaN,NaN,NaN,NaN
2060,798820a6-21e7-474c-9cff-dd209c93f9e9,32.0,Male,Brazil,Android,Simulation,6,27.59,Minnow,NaN,NaN,NaN,NaN
2087,d78dc510-e5b0-4d84-812b-1350ec8c3ce3,23.0,Male,Canada,Android,Role Playing,12,11.54,Dolphin,NaN,NaN,NaN,NaN
2106,09b47f98-bbfd-4729-a232-451beededcb8,18.0,Male,Netherlands,Android,Sandbox,6,10.00,Minnow,NaN,NaN,NaN,NaN
2125,89fbce0b-af13-4543-946c-dac2a651bf66,33.0,Female,Brazil,Android,Sports,13,20.46,Minnow,NaN,NaN,NaN,NaN
2155,18f29910-d46b-46a7-96eb-329e57570956,51.0,Female,Mexico,Android,Strategy,7,12.90,Minnow,NaN,NaN,NaN,NaN
2190,23b63dd0-4c87-441a-9b12-d1e4a7073186,27.0,Male,UK,Android,Adventure,11,27.78,Dolphin,NaN,NaN,NaN,NaN
2198,2508ada3-561b-468f-81ec-d5605cf7f24a,27.0,Male,Sri Lanka,iOS,Puzzle,8,21.66,Minnow,NaN,NaN,NaN,NaN
2201,2c6b6997-cfd5-4873-85b7-6661b70e6c28,52.0,Male,Switzerland,iOS,Card,3,26.11,Minnow,NaN,NaN,NaN,NaN
2208,cbc5a536-ce36-4a96-9fd9-7409a3033404,49.0,Male,Netherlands,iOS,Sports,8,32.54,Minnow,NaN,NaN,NaN,NaN
2244,16509bac-38c3-4b4f-94cd-ea15370873f5,46.0,Female,India,iOS,MMORPG,13,19.73,Minnow,NaN,NaN,NaN,NaN
2248,9a980540-a501-4e1f-829f-4f1dc1ec2659,39.0,Male,Canada,iOS,MOBA,12,28.41,Minnow,NaN,NaN,NaN,NaN
2257,11e44d35-9b14-4736-a57f-e4b61399ab2f,42.0,Female,Iran,iOS,Fighting,4,34.23,Minnow,NaN,NaN,NaN,NaN
2269,156410d7-f84f-4f32-bc15-7057948344c1,33.0,Female,Netherlands,iOS,Action RPG,13,17.08,Minnow,NaN,NaN,NaN,NaN
2292,bd057cb8-9afa-4643-a272-a6afa3ffff58,45.0,Female,Germany,iOS,Battle Royale,5,10.19,Minnow,NaN,NaN,NaN,NaN
2293,922b6de8-97b3-4714-9093-173cea826d30,42.0,Male,Saudi Arabia,iOS,MOBA,12,26.94,Minnow,NaN,NaN,NaN,NaN
2315,75b01e3a-6e7b-4328-91d1-5339b609eb85,13.0,Female,Mexico,Android,Action RPG,9,16.35,Minnow,NaN,NaN,NaN,NaN
2324,ace117d3-0682-477a-bfce-db9890cf010c,14.0,Female,Russia,iOS,Strategy,15,33.97,Minnow,NaN,NaN,NaN,NaN
2329,bf4f5a88-d0b7-4311-ba5d-a0a877ba7328,41.0,Female,Russia,Android,Card,10,29.46,Minnow,NaN,NaN,NaN,NaN
2333,9f0c3f94-d9e0-4924-836f-fe6f9eb3dbb9,54.0,Male,Brazil,Android,MMORPG,9,29.59,Dolphin,NaN,NaN,NaN,NaN
2378,3177fe4a-89dd-4aa9-ab77-a27ded2b6bc8,23.0,Male,China,iOS,Action RPG,9,15.73,Whale,NaN,NaN,NaN,NaN
2457,657ee2f7-aa00-4115-b066-137e84effa44,43.0,Male,Canada,Android,Casual,16,24.10,Whale,NaN,NaN,NaN,NaN
2466,bb579912-0a17-4fda-a5c3-36b222f8a721,45.0,Male,China,iOS,Card,12,28.25,Minnow,NaN,NaN,NaN,NaN
2499,030bf099-2381-4cd2-85ee-9cd7577bd7d0,50.0,Male,Germany,Android,Sandbox,13,23.69,Minnow,NaN,NaN,NaN,NaN
2509,633f5560-56f3-49b7-9ebd-d2486a222792,42.0,Female,Mexico,Android,MOBA,17,17.34,Minnow,NaN,NaN,NaN,NaN
2512,670e1056-1846-4832-84cd-c17372b56e64,20.0,Male,USA,iOS,Battle Royale,7,32.97,Minnow,NaN,NaN,NaN,NaN
2523,f6f0a59c-9971-4bf1-8aac-c738e41d9f5c,22.0,Male,Egypt,Android,Puzzle,11,11.28,Minnow,NaN,NaN,NaN,NaN
2570,15e7af42-e5df-4afe-b076-cf80c6831dd7,49.0,Male,Turkey,iOS,Sandbox,11,33.17,Minnow,NaN,NaN,NaN,NaN
2582,8b509f38-13a0-4894-9bad-c3a7061d4f5b,45.0,Male,Mexico,iOS,Sandbox,15,32.68,Minnow,NaN,NaN,NaN,NaN
2600,0d24b4f1-9686-4f77-95d1-31c5454bbd4d,47.0,Other,China,Android,Battle Royale,11,33.40,Minnow,NaN,NaN,NaN,NaN
2637,79bfba96-0b30-4fd7-8641-41a1dc49a16b,18.0,Male,Italy,iOS,MMORPG,13,16.56,Minnow,NaN,NaN,NaN,NaN
2698,e50b67b1-86ce-42f4-a424-0ac7847d50e4,38.0,Male,Germany,iOS,Role Playing,11,12.45,Minnow,NaN,NaN,NaN,NaN
2718,0079a83f-b03c-4c0e-be39-142af64e5f7d,17.0,Female,Denmark,Android,Simulation,18,17.07,Minnow,NaN,NaN,NaN,NaN
2721,3574b11e-0614-482b-8131-a52f2a0dee95,54.0,Female,Switzerland,Android,Puzzle,9,16.16,Whale,NaN,NaN,NaN,NaN
2729,92a5985c-59d6-4ab3-82a0-725c456d4a4a,18.0,Female,Italy,Android,Card,9,11.01,Minnow,NaN,NaN,NaN,NaN
2771,069f36eb-db2a-43a9-b52d-30d60f4745b7,20.0,Male,Japan,Android,Role Playing,9,20.65,Minnow,NaN,NaN,NaN,NaN
2776,afd4931f-e925-428d-b5e5-e6b90b588c40,43.0,Female,Netherlands,Android,Simulation,10,13.09,Dolphin,NaN,NaN,NaN,NaN
2795,b6e97633-f7c2-4603-ad2d-7a3d4102130d,16.0,Female,Denmark,iOS,Casual,11,31.39,Dolphin,NaN,NaN,NaN,NaN
2798,1b081faf-f75c-4440-85b4-8acdaf6f5eb5,47.0,Male,Egypt,Android,Adventure,12,16.14,Dolphin,NaN,NaN,NaN,NaN
2799,c1e5be50-4e0c-4338-9e4b-0d01b9e089d7,18.0,Male,Switzerland,Android,Action RPG,14,15.68,Dolphin,NaN,NaN,NaN,NaN
2808,b760bd8f-84d4-4bb6-8843-59c19bf7c46e,54.0,Female,Australia,Android,MOBA,11,15.20,Minnow,NaN,NaN,NaN,NaN
2822,49b09063-601f-46d9-b38f-2f43d44be003,19.0,Male,Norway,Android,Role Playing,6,17.27,Minnow,NaN,NaN,NaN,NaN
2835,6476aae8-4cad-4c96-aa4e-a52ad3f95f1f,47.0,Female,Russia,Android,MMORPG,7,20.62,Minnow,NaN,NaN,NaN,NaN
2849,91cac715-5d30-4cdc-8dca-ae45935bc086,22.0,Male,Japan,Android,MMORPG,10,27.65,Minnow,NaN,NaN,NaN,NaN
2879,2c036233-9c0a-4a7f-b724-bbdcc5d91559,NaN,Female,Japan,iOS,Strategy,13,27.67,Minnow,NaN,NaN,NaN,NaN
2930,3048af6d-baae-4191-8bdf-817c23661235,49.0,Male,Mexico,Android,Battle Royale,7,29.93,Dolphin,NaN,NaN,NaN,NaN
2990,d33756cf-dc49-416e-bde2-603371708a21,23.0,Male,Japan,iOS,Role Playing,8,26.30,Minnow,NaN,NaN,NaN,NaN
3012,efd47f71-4363-483f-89ba-d87e277a3c2e,35.0,Male,Germany,iOS,Role Playing,11,23.41,Minnow,NaN,NaN,NaN,NaN
3018,8c19377e-ac67-4592-bb9a-ab6eff586782,17.0,Male,Canada,iOS,Sandbox,14,9.83,Minnow,NaN,NaN,NaN,NaN

In [6]:
missing_purchase_record = games.loc[
    games['InAppPurchaseAmount'].isna(),
    'SpendingSegment'
].value_counts().reset_index().rename(columns={'count': 'MissingPurchaseRecords'})

missing_purchase_record

  SpendingSegment  MissingPurchaseRecords
0          Minnow                     111
1         Dolphin                      20
2           Whale                       5

### Checking df's Shape

In [7]:
games.shape

(3024, 13)

### Getting df info in order to undertand datatypes

In [8]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         3024 non-null   object
 1   Age                            2964 non-null   float64
 2   Gender                         2964 non-null   object
 3   Country                        2964 non-null   object
 4   Device                         2964 non-null   object
 5   GameGenre                      2964 non-null   object
 6   SessionCount                   3024 non-null   int64
 7   AverageSessionLength           3024 non-null   float64
 8   SpendingSegment                3024 non-null   object
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   float64
 11  PaymentMethod                  2888 non-null   object
 12  LastPurchaseDate               2888 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 307.3+ KB

### Missing values in purchase-related columns are expected and represent players who have never completed an in-app purchase.

### Checking uniqueness of UserID

In [10]:
games['UserID'].nunique()

3024

In [11]:
games[['Age','Gender','Country','Device','GameGenre']].isna().all(axis=1).sum()

0

In [12]:
games[['Age','Gender','Country','Device','GameGenre']].isna().any(axis=1).sum()

291

### Missing values in demographic variables were preserved. Since they represent less than 10% of the dataset and are unrelated to purchase behaviour, they were excluded automatically from analyses requiring those specific attributes rather than being removed or imputed.

# Duplicates Checks

In [16]:
games['UserID'].duplicated().sum()

0

In [17]:
games.duplicated().sum()

0

### No duplicated player IDs or fully duplicated records were found. Each row represents a unique player, confirming the dataset granularity (one row = one player).

# Data Type conversion

In [20]:
games

                                    UserID   Age  Gender       Country  \
0     c9889ab0-9cfc-4a75-acd9-5eab1df0015c  49.0    Male        Norway
1     7c9e413c-ecca-45f2-a780-2826a07952a2  15.0    Male   Switzerland
2     fd61e419-1a92-4f43-a8c7-135842ad328a  23.0    Male         China
3     bdb7f6d1-ff9a-468c-afe7-43f32a94293e  31.0    Male        Mexico
4     aa7eec14-4846-47b9-b879-9c98038cda04  37.0  Female         India
5     992232c1-a563-4986-aa8b-b70d687d374f  38.0  Female         China
6     702bafd0-9a08-4269-801e-faf32f9f3ca5  20.0  Female         Italy
7     fc470ea9-111f-4637-a9ff-7162d81e2ec3  34.0  Female       Denmark
8     9b2efc1e-cd4b-48ab-b893-438d57855efa  38.0    Male         Japan
9     25723b60-ea5b-4aff-9f23-97fdf5e98c58  46.0    Male        Russia
10    2bb44e49-c28d-4023-ac75-33d92cb77870  29.0    Male   Switzerland
11    a516f724-6b0f-438c-b20b-59f5f35ab06a  31.0    Male        Sweden
12    f72780cf-bccf-4ae5-8c12-09ee9d511322  30.0  Female     Australia
13    659f30ff-48f1-4e76-8f82-312d98e1ba76  24.0    Male        Turkey
14    34c56aa2-33c0-40c0-af9b-6c5b45929851  21.0    Male   South Korea
15    ae1ccfa2-8967-4981-be8f-a5c3b0f9f394  35.0    Male   Switzerland
16    bb0cf750-9fd2-4329-acc8-dc40dedaff3d  37.0  Female         Japan
17    cf1326be-4810-4b4d-bbc9-ff7b8c22d5ab  45.0    Male  Saudi Arabia
18    784fa153-301d-4286-adf5-3459e04e8a97  14.0  Female     Sri Lanka
19    9f1bd962-1ace-403e-aabb-eda9bd08e999  47.0  Female        Sweden
20    2cd9ff69-2a0d-4df7-82d5-400d609f66f5  35.0  Female        Mexico
21    d17030c2-e861-4028-aa03-23b18d239a40  14.0    Male         Japan
22    9b7c844f-1891-49da-a71d-b0b2719deda5  21.0    Male        Canada
23    2bf7d319-fba5-4d64-9187-358045a4ed40  54.0    Male        Canada
24    bab46c87-b7a7-4e1c-b56f-d1c8d2897733  47.0    Male       Denmark
25    902744c6-0620-47d6-92aa-b1d719b1d50f  52.0    Male     Sri Lanka
26    38041854-4fcc-41f7-a662-cf466afce86f  25.0    Male         Italy
27    cc7fffae-d126-4f3b-bbc4-c81213b6bf69  51.0    Male         India
28    03e7dc1d-dfe5-4677-aff4-239b6a60ad7c  18.0    Male   Switzerland
29    0d4f2cd8-6cee-4133-8cb2-435a0f6d19ef   NaN  Female        Russia
30    1afae40f-9b90-4710-a024-13d1d2b4266e  32.0    Male        France
31    2868c7dc-a4bc-4143-8256-334e29ec7458  54.0  Female           USA
32    8b27e55c-6841-4e55-ad1d-a953319e7839  34.0  Female           NaN
33    51632073-5433-48ef-a95f-a519029bb068  30.0  Female            UK
34    caddf020-37f9-42c6-b9d3-cf256901e2a9  31.0  Female   Netherlands
35    3d303a23-7484-45ec-ac02-e7e533b6b1f3  43.0    Male        Canada
36    c6301a66-20d3-4bd7-9ba5-664de4f1814b  49.0    Male   South Korea
37    9df52d99-a9d8-45d4-804d-d0288f9c88f2  54.0    Male        Norway
38    078c53b3-d2f8-4587-a779-d66661ed6351  38.0    Male        Norway
39    609ec77e-7c64-4486-a77d-da39f5e21576  17.0    Male  Saudi Arabia
40    b6208d5f-f05f-4b64-a9be-f0e3262c3952  19.0  Female           NaN
41    cb88b1cf-7ccc-4c4f-98b6-d6906c1bbb20  38.0    Male        Mexico
42    05ef5257-cb10-41a7-93be-616389d660f2  34.0    Male     Australia
43    daa87ce2-9524-437b-96f5-d862e44ba2a6  20.0  Female         Egypt
44    2059ae35-b1ea-4c2a-bbce-b89233c30938  32.0  Female         India
45    11826044-01a7-4201-af8a-5a93cc6a9b38  16.0  Female         Spain
46    69f06b32-f62f-4cf8-b5f2-c33c16ec646c  36.0    Male            UK
47    533679ef-f6a5-450d-858b-92a7a2e10de4  48.0  Female        France
48    5e12bef2-00c7-4634-b3b2-b0926e9cb9fc  35.0    Male        Brazil
49    f60f1c9a-d523-4648-a09c-7928e79fb2be  50.0    Male            UK
50    9c3598c6-6cd4-4da2-81ed-a8053987aa80  33.0  Female         Japan
51    e29badd2-8522-4287-bd03-a80fe9b71548  44.0  Female        Canada
52    2f9b59a8-8fa4-48cf-abec-3f3dd76aaf86  36.0  Female   Switzerland
53    536b79a9-29ac-4636-ae84-f4caff4b4ba0  29.0    Male           USA
54    d7b8a563-a467-4b0a-ad49-476e778e2417  25.0  Female        Sweden
55    3941a6e4-c925-4016-9701-99dacd2b8c81  52.0    Male    Bangladesh
56    b5084cbd-e884-4626-987a-91b4d1506d0d  18.0    Male         Spain
57    26cead3d-1110-410d-ab56-6e4c54c2d268  18.0    Male         Japan
58    dc8284d9-82a4-46b2-b871-50348b048411  17.0  Female         India
59    b5c61dc0-138d-4d49-ae4a-c4ca75787cb2  49.0    Male   Afghanistan
60    831776e9-a34f-4ea7-a68c-d453907cc5f2  40.0  Female         Japan
61    402ee755-ca98-477f-8c8d-a54fc4fa9c29  26.0    Male     Australia
62    b8515403-f053-45b6-9855-735e939cbaaa  50.0    Male            UK
63    75c92497-1ce3-4fff-8390-7fd40ccdcdc0  47.0    Male        Canada
64    f995f3e3-ffc4-4eed-abd3-c23ca495f86a  44.0    Male        Norway
65    4b416d1d-bd9e-4bfc-b4c9-0597a983fffd  13.0    Male     Australia
66    bb33b2f4-a9f7-49f0-893a-1e37582656d8  33.0    Male  Saudi Arabia
67    6dcd7ef4-f90d-4745-b0d7-514c8d318ee6  24.0  Female    Bangladesh
68    c89433ee-4f4f-42f3-98e6-8ffa5c82a199  29.0  Female       Denmark
69    a6164e91-512e-4fb3-9fd7-e1b81ab01306  52.0    Male        Turkey
70    bbe10e54-9d0f-4ded-b144-9540adaa29ae  38.0  Female         Egypt
71    f3b619e3-454a-4afa-8727-eb260a7cf161  26.0    Male   Afghanistan
72    a8eb7f0a-2b5b-4e33-b735-bdbcd167e6c9  50.0  Female        Russia
73    491dd37f-368b-4170-a53e-bb50bd2cf501  42.0  Female        France
74    a2cff92e-52de-4e63-8318-4dfb42c4a445  20.0    Male     Australia
75    5de124a0-1cb3-4486-87cb-9699cda32a6c  19.0    Male        Brazil
76    8bfa625a-9651-4818-a1a2-e1cc6985f12c  31.0  Female         India
77    a125ceb7-abc0-4e40-a418-2023a5c38edb  30.0    Male           USA
78    d88da455-eacb-4fc0-b7d8-9ee22f1c0ffa  18.0    Male  Saudi Arabia
79    47b6299d-8f0e-4cb3-8275-f8bc157318c8  21.0    Male        Canada
80    9e57ae3d-1a32-4913-b522-8b576f672731  37.0   Other        Mexico
81    55b14ef0-9383-48b5-9e88-b5814331b23d   NaN  Female            UK
82    3e38f13d-0869-44c3-aec1-f204f7a370ef  33.0    Male        Turkey
83    5f20a679-6f98-4bbd-b463-819edc54b2b9  28.0    Male   Netherlands
84    523abcfa-4d38-4a89-b5f5-ce5e4f215fcf   NaN    Male    Bangladesh
85    bb8e3213-005c-4565-81a3-27fdbf103c57  39.0    Male         Japan
86    d5913936-3c9e-4b38-96ed-6d151d5f3e95  51.0    Male   Switzerland
87    6c2a5488-7147-4d3b-b05d-73991b8c8730  51.0    Male        Turkey
88    cd5a9e40-7add-48fb-8adf-99796d5072fb  50.0    Male       Denmark
89    f8f073c4-5291-4675-a58f-d178815d0d96  22.0    Male         Egypt
90    713e8104-54bd-470c-a778-3fbc4a9290a0  24.0    Male         Spain
91    e679e2e0-b0b0-4522-96d0-504f0e7cbf06  25.0  Female       Germany
92    80c3199d-e975-4ccd-85ef-13c59aa1f805  28.0    Male        Turkey
93    9d7e9a20-197d-4104-9886-808d8b9afe03  23.0  Female   Switzerland
94    a6eccba4-c776-4d6d-97b0-facfb3198010  39.0  Female          Iran
95    e02f17d6-dec7-440c-ad82-3c5b78120050  20.0  Female         India
96    96719446-f2bc-47cf-83e5-3f74da1ea9e4  36.0    Male            UK
97    f5bcac4c-23dc-41aa-86f8-6a7e62262f89  28.0  Female   South Korea
98    ba8e2c67-c8d7-4eea-9140-de8b5a8c7408  53.0    Male          Iran
99    24cbe32b-e245-4402-a633-a4bb912b6c53  26.0  Female          Iran
100   7274e19d-b3cc-4e0c-9260-4fd47a7355f0  17.0  Female         Italy
101   f0606a81-b49e-42ec-8439-5a2c8537ba31  13.0    Male   Netherlands
102   1a1197fb-e7c7-498f-8f62-740898e0ad28  38.0    Male    Bangladesh
103   36fffb0c-b111-40a3-9d01-b960914e05c3  49.0    Male         China
104   2712e660-4d07-4b97-ae2f-f260de26762f  49.0    Male   Netherlands
105   5f40e5c4-5bdf-49cd-a1c5-0db095391e26  29.0  Female           NaN
106   a1569884-f0ba-4715-9625-79bd34e31a29  33.0    Male  Saudi Arabia
107   1bd97852-263c-43ed-afbd-515619bb6713  27.0    Male         Spain
108   44f04607-d70e-43e7-9946-cfccd2c506ff  26.0    Male         Spain
109   6a3e7755-15d2-4261-b6b9-2040975ba87c  24.0  Female            UK
110   765f67bd-0006-4e9a-b3b1-d017e9e42fa3  22.0  Female        Brazil
111   65c9070d-a1dc-46a1-8041-f1ff52f0b476  44.0  Female   South Korea
112   63c439e3-2274-4107-9dc5-e93cd5325423  24.0  Female     Australia
113   ea67c7b3-f672-4d1f-a87c-b6ad687805d7  52.0    Male        Mexico
114   8840c167-29ab-4573-ba75-be52c1b9e508  20.0    Male   Afghanistan
115   e9eadb83-df6f-4f35-a218-b11768a69681  40.0    Male        Norway
116   1d725650-a2de-4bde-b2c1-0a2116831067  19.0    Male         China
117   d4cb7f92-952d-4528-b4bb-96d4a9bd038a  37.0    Male         Italy
118   bdac696e-6890-437b-97cc-6979587048bd  36.0    Male         Egypt
119   3e5c7e39-a2e3-4e94-a2fb-210453694387  51.0    Male       Germany
120   8bbdc323-6d6a-47f7-9ef9-0ed2d2d6cb0a  26.0  Female         Italy
121   a6fa3862-4789-466e-8f29-f08d754e9e8c  34.0    Male         Spain
122   1f582143-b515-493b-86c9-8a36fedffabe  25.0  Female           USA
123   40462d77-d324-497b-80f8-f94c9bcfb5ef  27.0    Male    Bangladesh
124   f952dd17-61b1-4f47-a01f-19e66d0b84dc  40.0  Female        Sweden
125   b896ef32-5e12-4eed-a8a3-b144188deb8f  42.0     NaN         China
126   c1833346-8b2d-4775-bdb9-de5e417013e9  50.0    Male        France
127   92ef0133-13ca-4f43-bedb-bf91815bf36f  43.0    Male     Sri Lanka
128   2da8404d-b63d-4c9c-a0f4-35aff413d004  26.0    Male         India
129   b4ede4a8-eea4-4416-a89a-5a92a700a1f2  36.0    Male         India
130   b23912e7-0c77-4bb1-a4c8-3c6937a6b24f  36.0    Male         India
131   d6015577-c9c0-4570-af35-db924ca0bdc8  52.0    Male         Spain
132   c97c7aeb-5d60-4f9c-9e55-cdce38c7e8e1  43.0    Male        Mexico
133   ed7b7b9c-22a6-4558-8f8a-8a4556b2e093  13.0  Female   South Korea
134   f7668438-a3c8-4a02-bd33-6840b93697de  18.0  Female    Bangladesh
135   247a935c-a5c4-46cb-aeaf-f553682d79a9  53.0  Female         Spain
136   be14daac-e920-483b-9e35-cba65b3bfd92  46.0  Female         India
137   1c6b1ac6-1002-4b36-8fd5-1c10ae5b632c  23.0  Female        Mexico
138   d1ff9108-e92c-44de-b5ea-c529d1783957  41.0    Male        Mexico
139   b4bc9ecf-7216-4ca9-bc91-5d590ddd1a9d  14.0    Male        Canada
140   ed298fb4-3ea3-4c92-a538-7fe6fe7a7bb5  18.0  Female          Iran
141   5b49451a-0ed2-42c0-89f1-e5dbd4ee61da  18.0  Female         China
142   ab59cc4b-5dbd-44f2-ae12-29f41788ceda  33.0     NaN           USA
143   43c40cd4-b36f-45f5-b69d-1d6a8c4e152f  14.0  Female   South Korea
144   fcede627-64f9-47f3-a2fb-06e1601eb9f3  25.0    Male        Mexico
145   91febda3-377e-457b-9f1d-8f4970ede405  22.0    Male        Canada
146   0e90ac96-4cb4-4cdd-be24-dee5f09b553b  44.0    Male         China
147   5ca89fdb-c686-406e-94b4-6e6002ff1f6c  52.0    Male       Denmark
148   46defc98-35ab-4143-907b-2079fdee31ba  35.0  Female         Japan
149   1d400a74-33a2-4094-8066-674e04ce1a70  15.0  Female   Afghanistan
150   c703b6da-38c9-471a-b24d-d018211f9f85  13.0    Male     Australia
151   331deea7-19c1-4927-892b-76174d56ec49  29.0  Female         Spain
152   183a3fa8-6e20-4e1b-a691-7f7dcebe7a33  48.0    Male       Germany
153   2a783ac4-7027-4262-b320-c9149cffc55e  32.0    Male        Turkey
154   3fdb270f-8483-45fd-9ab4-db3052986187  14.0    Male   Switzerland
155   d8d662bd-4aa9-4cd7-86aa-1bc17f91294c  27.0    Male         Italy
156   a48782e4-26df-4f96-93cf-5e257242f1ed  20.0    Male        Brazil
157   b24d9feb-ba9d-43e7-ba75-f23bdfc550b3  53.0    Male        Canada
158   26eb8952-31d6-44a4-b20c-062176a5863c  22.0  Female         India
159   45aec45a-b3b8-4154-a53b-38cf145fffd5  16.0    Male         India
160   7c28ad05-8b95-4859-88ec-f00daaf02b99  28.0  Female        Turkey
161   2a88cfbc-0304-4d3c-beae-9a6537f9ccf4  16.0    Male           USA
162   6225ea4b-e767-4b86-98ee-ff16d5cc6553  43.0  Female   South Korea
163   9c00ee70-d6c0-48e7-ae8c-86624d8242d4  29.0  Female         Egypt
164   9d36db05-510d-4d8c-b7a9-4d2d9e5bb7c5  43.0    Male         India
165   bcb6e14f-1ff4-4d64-bf00-d41fd29961ad   NaN  Female        Brazil
166   b99eb8c7-f6c9-4d78-95ee-c092b374e877  35.0    Male         Japan
167   c0b33c59-121b-4ecd-8afc-b15a56f05f98  24.0    Male        Sweden
168   6e93617a-0fcc-4fdf-90cd-4e62f1feea2a  23.0    Male     Australia
169   8a324a49-8484-48b1-91b2-a97c5371ab03  13.0    Male         India
170   608d9f0b-26ca-40ca-bef1-8028a610efd5  19.0    Male   Netherlands
171   37af1ed6-33b9-46ee-887a-38cce6c8f89a  32.0  Female        Turkey
172   7dc3d885-47b6-4ff1-bf91-610920fefb62  30.0     NaN   Afghanistan
173   5f79202e-0406-491b-989e-d2449e943c4d  37.0    Male         Spain
174   7fe571aa-451b-4fed-b1d8-6b976985d30a  51.0    Male            UK
175   bc42d13e-06b4-4ac5-aa4b-4909f201829a  33.0    Male         India
176   1bfc05b0-5c46-4652-a050-3623aa98c63d  39.0    Male    Bangladesh
177   a384e317-6490-4f5f-9042-db164b856a27  45.0    Male  Saudi Arabia
178   96cece19-9d64-48c0-8453-cd3cfc54b13f  45.0    Male         India
179   b79d286f-4d90-43bb-8f6e-f7fd319eadad  40.0    Male    Bangladesh
180   8c9b4eaa-d9fe-42ab-9a03-e0eb37d9bbfe  51.0  Female   South Korea
181   b64870a7-b26b-42f3-9e08-583d869ec2bc  27.0  Female   South Korea
182   bce6f198-360d-4ecc-ba91-63ec5f4428e7  52.0    Male         Italy
183   0a27824c-f44c-41d2-bbdb-a72f7e05976d  17.0    Male          Iran
184   fe5e6540-a6d4-4f52-8f6c-49f39a798753  30.0    Male        Mexico
185   f7ecc1c5-d64d-4f22-b389-f2447e756d0f  53.0  Female     Australia
186   0ac34a31-e5b0-450e-9b78-807f4dc920bd  36.0    Male   South Korea
187   9c90326e-28ba-4dbd-bf48-d182f5c5ec87  46.0    Male        Sweden
188   bd726fee-fde2-4063-8532-3f16aa8e2a56   NaN    Male   Afghanistan
189   9de29aeb-075b-462d-9049-72133694847a  14.0  Female       Denmark
190   32e6555f-1157-483f-b9ed-be0696940fc8  49.0  Female         India
191   3e18d192-0991-475a-9fbc-ef448ba7df8e  41.0    Male         Italy
192   8dd3d210-13f7-4ec2-a2d7-924d7d3a1dd1  35.0     NaN   South Korea
193   2de4aa24-87fe-4fa8-928f-f2e8a2407cce  33.0    Male         India
194   b7f2effd-6c0b-4cfb-9116-a53b2828ecf7  49.0  Female    Bangladesh
195   0202a126-e63e-4a78-9ca2-f4ffef1d1558  35.0    Male         Italy
196   a18c92c3-5270-4abc-9147-238d3f08944d  29.0    Male        Norway
197   815cecaf-fce3-4d33-b308-97e563da3d9e  42.0    Male         Egypt
198   7585a97e-3b6b-4e77-80d2-265445a0aceb  52.0    Male        France
199   d3095600-2911-4658-a0e4-9b3e71ba0e40  15.0    Male   Netherlands
200   9e6fe49e-5f4e-421f-9de7-08c5745588a9  14.0     NaN        Brazil
201   a8ae7b9d-af5f-4384-b42c-368dc37e7e5c  19.0    Male        Norway
202   ba0a0643-db22-4441-a188-e509246a682b  31.0  Female     Sri Lanka
203   9f844184-9fcc-4ddf-948e-a8a06a79bf45  30.0    Male     Sri Lanka
204   1a4ab072-e221-42f5-9b79-6da7352e1f17  18.0    Male        Brazil
205   b86d25d2-b624-458a-a7ad-a3460c466e99  42.0    Male         Spain
206   950d5816-1db4-4107-86b1-b0eb93a8fdf7  14.0    Male       Germany
207   08a3aa8f-88cc-4f3f-a69c-5b002ad7aaad  43.0  Female         Italy
208   e035314c-dd1a-43f5-92c7-27fc090e7562  49.0    Male     Sri Lanka
209   bcf4d674-d9cc-4c41-b90c-f69bc332235d  52.0    Male   Afghanistan
210   f34384a2-7325-4713-a0d8-920daed8a3de  30.0  Female   Netherlands
211   c6a03f68-58b9-44a4-922f-4031ab1136a7  31.0  Female        Mexico
212   18bb4c37-a9cb-4706-9210-57011be1c66f  21.0  Female         Italy
213   3b8761c1-27d9-4957-bd5d-aaf09f5409ff  47.0    Male     Sri Lanka
214   2b5f9d97-d98a-48ff-9fe0-42894333b36a  16.0    Male   South Korea
215   c6a5c9dc-ed1e-4f35-a000-b6e7b2c6ef70  41.0  Female        Mexico
216   82edc8a5-83c2-4894-807d-234c912e5477  45.0  Female  Saudi Arabia
217   b5810a9e-6ff2-476f-96c5-4b285cebbac1  22.0    Male        Mexico
218   e5689efe-ffba-4c62-8e4f-0d2da3c79dd0  19.0    Male       Germany
219   81cab772-c5d5-46a3-8c45-2ff02a9d21d5  37.0  Female     Sri Lanka
220   2afe4941-c293-4068-83dd-2bc72b1b7123  32.0    Male    Bangladesh
221   b22003d2-4698-4c16-a5b3-eed4a494d0a9  17.0  Female         Japan
222   ee1a179f-ecb3-4dd9-9b59-11823faf46e4  20.0    Male        Norway
223   fcb50b3c-7efa-48c2-bb91-228a8e401b89  40.0  Female        Mexico
224   8a91fa57-d4e4-43e9-8684-456b108237d6  51.0    Male   South Korea
225   20865a0d-733a-4d1d-9997-02e67f350932  20.0  Female          Iran
226   c4fedcdb-0ed7-47b6-ac7e-5fbcb2421fb4  29.0  Female        Norway
227   ba478a10-df2b-4c63-88c7-185f740e3738  20.0  Female   Afghanistan
228   21923a3e-6de2-44f2-8839-c9e61b46765a  13.0    Male           USA
229   24a5635b-34f2-436d-b9e6-4d155dcecee1  30.0  Female     Sri Lanka
230   f0748d5b-661c-4f2b-b236-2dd399809aab  38.0  Female     Australia
231   b78c392f-b9aa-4366-b712-c7e84bdc6c35  43.0  Female    Bangladesh
232   6f16f229-3ecf-4618-b571-c1e902734af3  14.0  Female           NaN
233   583599e7-193b-4019-9e03-27e687d5bb34  25.0    Male   Netherlands
234   49656b72-f958-4dca-84db-ce772059a6f1  26.0  Female       Germany
235   489b35f4-7612-4d31-a6cb-1bb127b88ae3  47.0  Female          Iran
236   9cd3e13b-de09-49d1-9d6a-0f35e5a66523  25.0  Female        Turkey
237   9f653d6c-0ee6-4390-a238-ed39024348f4  15.0  Female         Spain
238   fd116d08-e23f-495f-a323-44d6d9a21a8e  14.0    Male         Japan
239   158aeb25-5f92-45c3-ae37-8b44b5fa5172  17.0  Female        Norway
240   6c7b3db2-6b53-481c-897e-358a7e310323  40.0    Male   South Korea
241   3dd22990-c352-491c-9d18-3b40cf762492  16.0    Male         Spain
242   7377eeb5-20da-42ac-8ef3-a2d79e9a367d  18.0    Male       Denmark
243   c0f58ea1-0d56-4bae-a379-77833f58e1ec  36.0    Male          Iran
244   2df6aca1-4c6a-4e77-8dff-fa5fc8609726  46.0  Female           USA
245   0e1d1d07-c427-4e44-a015-ed199199d982  39.0  Female        Mexico
246   c2a5f183-390b-40f3-b9fd-1a6acd64e968  13.0    Male         India
247   f9e77e0f-0e19-4609-b11a-128844cf34a9  19.0  Female         Egypt
248   d3d71ba1-6331-482b-ab2f-0f0810e3e310  43.0    Male     Australia
249   5575ca75-b875-42be-adc9-f068778ea73d  29.0    Male         Japan
250   c7ac31a3-cbc2-464a-a902-0cc67b9ddb60  51.0    Male        Brazil
251   28774c61-a933-4ae9-8503-cf5967e56d5c  21.0    Male         Egypt
252   fbd65117-f7c5-47b9-9162-7d3e643e79cd  19.0    Male   South Korea
253   868ab631-3057-4979-b233-5b307d20e475  21.0  Female     Sri Lanka
254   1bf14ea6-aab2-4d68-be04-832f9515b183  49.0  Female     Australia
255   836d7b01-1b32-438a-9e56-514a6494d848  40.0    Male        Canada
256   6d7c2868-79d4-40f5-94cc-c8300d6a409e  19.0  Female   South Korea
257   d39a96e7-f66c-4a1d-9073-c8f05dd315c5  19.0    Male        Sweden
258   39b4a4fb-a36b-4dc3-9c7a-e7f2ab21d02d  21.0  Female        Canada
259   83b88cd3-1b65-41a8-a3e6-1532085fda74  34.0    Male            UK
260   8e26c709-34ab-4db0-8d1b-80eddcc0aca7  28.0    Male   Netherlands
261   a8bf6828-3adb-41b0-8232-153737754604  47.0  Female        Turkey
262   b2afcd56-2fcd-4e09-ba68-547125cdec1a  36.0  Female           USA
263   4dc9a8b8-e379-4d24-a667-f34f9729852f  42.0    Male   Afghanistan
264   9ddd7102-a354-4612-9456-d9946e6583ad  22.0    Male       Germany
265   74d3c6b8-0f64-4a00-b021-39403c95c751  24.0    Male        Mexico
266   c7aacb9b-7b33-479c-aae9-ecd0aaddd50b  18.0    Male            UK
267   75a44ecd-8ba7-4833-8d98-5444adf1296c  52.0    Male        Russia
268   95ddad04-3639-4e5c-b098-63ec5f39cc6e  13.0    Male     Sri Lanka
269   c5e10c4c-16ff-4b8a-8014-3d74076546b1  45.0    Male           USA
270   e953bfe5-8b5f-407b-bb41-26b45ac4e752  49.0  Female            UK
271   1b8e312d-a914-4007-8f8a-6fc4d1754e85  30.0    Male       Germany
272   0778cc79-09e4-417a-b022-ccbf69d7865d  42.0  Female        Norway
273   bc331aeb-abf6-4cda-837a-fe0ee76d5df7  20.0  Female         India
274   f0b60984-56ea-4a30-8058-adef47617cdf  33.0  Female        Mexico
275   d3fdd03d-cb34-4127-a0e9-cb923101283d  25.0   Other   Switzerland
276   886b9aca-5d31-4065-a308-ddf1140fe728  21.0    Male       Denmark
277   0d15b643-977d-4ec4-9599-7c59b5ee3e73   NaN  Female        Mexico
278   a730f213-444f-460d-b28d-8ce751973bd9  49.0    Male        Turkey
279   a61e91e8-43a9-40b9-964e-c354110f0e43  29.0   Other       Denmark

In [21]:
games.dtypes

UserID                            object
Age                              float64
Gender                            object
Country                           object
Device                            object
GameGenre                         object
SessionCount                       int64
AverageSessionLength             float64
SpendingSegment                   object
InAppPurchaseAmount              float64
FirstPurchaseDaysAfterInstall    float64
PaymentMethod                     object
LastPurchaseDate                  object
dtype: object

In [22]:
df = games.copy() # a copy of our DataFrame has been created

In [23]:
df['LastPurchaseDate'] = pd.to_datetime(df['LastPurchaseDate'], format = '%Y-%m-%d') 
df['Age'] = df['Age'].astype('Int64')
df['FirstPurchaseDaysAfterInstall'] = df['FirstPurchaseDaysAfterInstall'].astype('Int64') # 'Int64' preserves the NaN
df['GameGenre'] = df['GameGenre'].astype('category')

In [24]:
df.dtypes

UserID                                   object
Age                                       Int64
Gender                                   object
Country                                  object
Device                                   object
GameGenre                              category
SessionCount                              int64
AverageSessionLength                    float64
SpendingSegment                          object
InAppPurchaseAmount                     float64
FirstPurchaseDaysAfterInstall             Int64
PaymentMethod                            object
LastPurchaseDate                 datetime64[ns]
dtype: object

In [25]:
df

                                    UserID   Age  Gender       Country  \
0     c9889ab0-9cfc-4a75-acd9-5eab1df0015c    49    Male        Norway
1     7c9e413c-ecca-45f2-a780-2826a07952a2    15    Male   Switzerland
2     fd61e419-1a92-4f43-a8c7-135842ad328a    23    Male         China
3     bdb7f6d1-ff9a-468c-afe7-43f32a94293e    31    Male        Mexico
4     aa7eec14-4846-47b9-b879-9c98038cda04    37  Female         India
5     992232c1-a563-4986-aa8b-b70d687d374f    38  Female         China
6     702bafd0-9a08-4269-801e-faf32f9f3ca5    20  Female         Italy
7     fc470ea9-111f-4637-a9ff-7162d81e2ec3    34  Female       Denmark
8     9b2efc1e-cd4b-48ab-b893-438d57855efa    38    Male         Japan
9     25723b60-ea5b-4aff-9f23-97fdf5e98c58    46    Male        Russia
10    2bb44e49-c28d-4023-ac75-33d92cb77870    29    Male   Switzerland
11    a516f724-6b0f-438c-b20b-59f5f35ab06a    31    Male        Sweden
12    f72780cf-bccf-4ae5-8c12-09ee9d511322    30  Female     Australia
13    659f30ff-48f1-4e76-8f82-312d98e1ba76    24    Male        Turkey
14    34c56aa2-33c0-40c0-af9b-6c5b45929851    21    Male   South Korea
15    ae1ccfa2-8967-4981-be8f-a5c3b0f9f394    35    Male   Switzerland
16    bb0cf750-9fd2-4329-acc8-dc40dedaff3d    37  Female         Japan
17    cf1326be-4810-4b4d-bbc9-ff7b8c22d5ab    45    Male  Saudi Arabia
18    784fa153-301d-4286-adf5-3459e04e8a97    14  Female     Sri Lanka
19    9f1bd962-1ace-403e-aabb-eda9bd08e999    47  Female        Sweden
20    2cd9ff69-2a0d-4df7-82d5-400d609f66f5    35  Female        Mexico
21    d17030c2-e861-4028-aa03-23b18d239a40    14    Male         Japan
22    9b7c844f-1891-49da-a71d-b0b2719deda5    21    Male        Canada
23    2bf7d319-fba5-4d64-9187-358045a4ed40    54    Male        Canada
24    bab46c87-b7a7-4e1c-b56f-d1c8d2897733    47    Male       Denmark
25    902744c6-0620-47d6-92aa-b1d719b1d50f    52    Male     Sri Lanka
26    38041854-4fcc-41f7-a662-cf466afce86f    25    Male         Italy
27    cc7fffae-d126-4f3b-bbc4-c81213b6bf69    51    Male         India
28    03e7dc1d-dfe5-4677-aff4-239b6a60ad7c    18    Male   Switzerland
29    0d4f2cd8-6cee-4133-8cb2-435a0f6d19ef  <NA>  Female        Russia
30    1afae40f-9b90-4710-a024-13d1d2b4266e    32    Male        France
31    2868c7dc-a4bc-4143-8256-334e29ec7458    54  Female           USA
32    8b27e55c-6841-4e55-ad1d-a953319e7839    34  Female           NaN
33    51632073-5433-48ef-a95f-a519029bb068    30  Female            UK
34    caddf020-37f9-42c6-b9d3-cf256901e2a9    31  Female   Netherlands
35    3d303a23-7484-45ec-ac02-e7e533b6b1f3    43    Male        Canada
36    c6301a66-20d3-4bd7-9ba5-664de4f1814b    49    Male   South Korea
37    9df52d99-a9d8-45d4-804d-d0288f9c88f2    54    Male        Norway
38    078c53b3-d2f8-4587-a779-d66661ed6351    38    Male        Norway
39    609ec77e-7c64-4486-a77d-da39f5e21576    17    Male  Saudi Arabia
40    b6208d5f-f05f-4b64-a9be-f0e3262c3952    19  Female           NaN
41    cb88b1cf-7ccc-4c4f-98b6-d6906c1bbb20    38    Male        Mexico
42    05ef5257-cb10-41a7-93be-616389d660f2    34    Male     Australia
43    daa87ce2-9524-437b-96f5-d862e44ba2a6    20  Female         Egypt
44    2059ae35-b1ea-4c2a-bbce-b89233c30938    32  Female         India
45    11826044-01a7-4201-af8a-5a93cc6a9b38    16  Female         Spain
46    69f06b32-f62f-4cf8-b5f2-c33c16ec646c    36    Male            UK
47    533679ef-f6a5-450d-858b-92a7a2e10de4    48  Female        France
48    5e12bef2-00c7-4634-b3b2-b0926e9cb9fc    35    Male        Brazil
49    f60f1c9a-d523-4648-a09c-7928e79fb2be    50    Male            UK
50    9c3598c6-6cd4-4da2-81ed-a8053987aa80    33  Female         Japan
51    e29badd2-8522-4287-bd03-a80fe9b71548    44  Female        Canada
52    2f9b59a8-8fa4-48cf-abec-3f3dd76aaf86    36  Female   Switzerland
53    536b79a9-29ac-4636-ae84-f4caff4b4ba0    29    Male           USA
54    d7b8a563-a467-4b0a-ad49-476e778e2417    25  Female        Sweden
55    3941a6e4-c925-4016-9701-99dacd2b8c81    52    Male    Bangladesh
56    b5084cbd-e884-4626-987a-91b4d1506d0d    18    Male         Spain
57    26cead3d-1110-410d-ab56-6e4c54c2d268    18    Male         Japan
58    dc8284d9-82a4-46b2-b871-50348b048411    17  Female         India
59    b5c61dc0-138d-4d49-ae4a-c4ca75787cb2    49    Male   Afghanistan
60    831776e9-a34f-4ea7-a68c-d453907cc5f2    40  Female         Japan
61    402ee755-ca98-477f-8c8d-a54fc4fa9c29    26    Male     Australia
62    b8515403-f053-45b6-9855-735e939cbaaa    50    Male            UK
63    75c92497-1ce3-4fff-8390-7fd40ccdcdc0    47    Male        Canada
64    f995f3e3-ffc4-4eed-abd3-c23ca495f86a    44    Male        Norway
65    4b416d1d-bd9e-4bfc-b4c9-0597a983fffd    13    Male     Australia
66    bb33b2f4-a9f7-49f0-893a-1e37582656d8    33    Male  Saudi Arabia
67    6dcd7ef4-f90d-4745-b0d7-514c8d318ee6    24  Female    Bangladesh
68    c89433ee-4f4f-42f3-98e6-8ffa5c82a199    29  Female       Denmark
69    a6164e91-512e-4fb3-9fd7-e1b81ab01306    52    Male        Turkey
70    bbe10e54-9d0f-4ded-b144-9540adaa29ae    38  Female         Egypt
71    f3b619e3-454a-4afa-8727-eb260a7cf161    26    Male   Afghanistan
72    a8eb7f0a-2b5b-4e33-b735-bdbcd167e6c9    50  Female        Russia
73    491dd37f-368b-4170-a53e-bb50bd2cf501    42  Female        France
74    a2cff92e-52de-4e63-8318-4dfb42c4a445    20    Male     Australia
75    5de124a0-1cb3-4486-87cb-9699cda32a6c    19    Male        Brazil
76    8bfa625a-9651-4818-a1a2-e1cc6985f12c    31  Female         India
77    a125ceb7-abc0-4e40-a418-2023a5c38edb    30    Male           USA
78    d88da455-eacb-4fc0-b7d8-9ee22f1c0ffa    18    Male  Saudi Arabia
79    47b6299d-8f0e-4cb3-8275-f8bc157318c8    21    Male        Canada
80    9e57ae3d-1a32-4913-b522-8b576f672731    37   Other        Mexico
81    55b14ef0-9383-48b5-9e88-b5814331b23d  <NA>  Female            UK
82    3e38f13d-0869-44c3-aec1-f204f7a370ef    33    Male        Turkey
83    5f20a679-6f98-4bbd-b463-819edc54b2b9    28    Male   Netherlands
84    523abcfa-4d38-4a89-b5f5-ce5e4f215fcf  <NA>    Male    Bangladesh
85    bb8e3213-005c-4565-81a3-27fdbf103c57    39    Male         Japan
86    d5913936-3c9e-4b38-96ed-6d151d5f3e95    51    Male   Switzerland
87    6c2a5488-7147-4d3b-b05d-73991b8c8730    51    Male        Turkey
88    cd5a9e40-7add-48fb-8adf-99796d5072fb    50    Male       Denmark
89    f8f073c4-5291-4675-a58f-d178815d0d96    22    Male         Egypt
90    713e8104-54bd-470c-a778-3fbc4a9290a0    24    Male         Spain
91    e679e2e0-b0b0-4522-96d0-504f0e7cbf06    25  Female       Germany
92    80c3199d-e975-4ccd-85ef-13c59aa1f805    28    Male        Turkey
93    9d7e9a20-197d-4104-9886-808d8b9afe03    23  Female   Switzerland
94    a6eccba4-c776-4d6d-97b0-facfb3198010    39  Female          Iran
95    e02f17d6-dec7-440c-ad82-3c5b78120050    20  Female         India
96    96719446-f2bc-47cf-83e5-3f74da1ea9e4    36    Male            UK
97    f5bcac4c-23dc-41aa-86f8-6a7e62262f89    28  Female   South Korea
98    ba8e2c67-c8d7-4eea-9140-de8b5a8c7408    53    Male          Iran
99    24cbe32b-e245-4402-a633-a4bb912b6c53    26  Female          Iran
100   7274e19d-b3cc-4e0c-9260-4fd47a7355f0    17  Female         Italy
101   f0606a81-b49e-42ec-8439-5a2c8537ba31    13    Male   Netherlands
102   1a1197fb-e7c7-498f-8f62-740898e0ad28    38    Male    Bangladesh
103   36fffb0c-b111-40a3-9d01-b960914e05c3    49    Male         China
104   2712e660-4d07-4b97-ae2f-f260de26762f    49    Male   Netherlands
105   5f40e5c4-5bdf-49cd-a1c5-0db095391e26    29  Female           NaN
106   a1569884-f0ba-4715-9625-79bd34e31a29    33    Male  Saudi Arabia
107   1bd97852-263c-43ed-afbd-515619bb6713    27    Male         Spain
108   44f04607-d70e-43e7-9946-cfccd2c506ff    26    Male         Spain
109   6a3e7755-15d2-4261-b6b9-2040975ba87c    24  Female            UK
110   765f67bd-0006-4e9a-b3b1-d017e9e42fa3    22  Female        Brazil
111   65c9070d-a1dc-46a1-8041-f1ff52f0b476    44  Female   South Korea
112   63c439e3-2274-4107-9dc5-e93cd5325423    24  Female     Australia
113   ea67c7b3-f672-4d1f-a87c-b6ad687805d7    52    Male        Mexico
114   8840c167-29ab-4573-ba75-be52c1b9e508    20    Male   Afghanistan
115   e9eadb83-df6f-4f35-a218-b11768a69681    40    Male        Norway
116   1d725650-a2de-4bde-b2c1-0a2116831067    19    Male         China
117   d4cb7f92-952d-4528-b4bb-96d4a9bd038a    37    Male         Italy
118   bdac696e-6890-437b-97cc-6979587048bd    36    Male         Egypt
119   3e5c7e39-a2e3-4e94-a2fb-210453694387    51    Male       Germany
120   8bbdc323-6d6a-47f7-9ef9-0ed2d2d6cb0a    26  Female         Italy
121   a6fa3862-4789-466e-8f29-f08d754e9e8c    34    Male         Spain
122   1f582143-b515-493b-86c9-8a36fedffabe    25  Female           USA
123   40462d77-d324-497b-80f8-f94c9bcfb5ef    27    Male    Bangladesh
124   f952dd17-61b1-4f47-a01f-19e66d0b84dc    40  Female        Sweden
125   b896ef32-5e12-4eed-a8a3-b144188deb8f    42     NaN         China
126   c1833346-8b2d-4775-bdb9-de5e417013e9    50    Male        France
127   92ef0133-13ca-4f43-bedb-bf91815bf36f    43    Male     Sri Lanka
128   2da8404d-b63d-4c9c-a0f4-35aff413d004    26    Male         India
129   b4ede4a8-eea4-4416-a89a-5a92a700a1f2    36    Male         India
130   b23912e7-0c77-4bb1-a4c8-3c6937a6b24f    36    Male         India
131   d6015577-c9c0-4570-af35-db924ca0bdc8    52    Male         Spain
132   c97c7aeb-5d60-4f9c-9e55-cdce38c7e8e1    43    Male        Mexico
133   ed7b7b9c-22a6-4558-8f8a-8a4556b2e093    13  Female   South Korea
134   f7668438-a3c8-4a02-bd33-6840b93697de    18  Female    Bangladesh
135   247a935c-a5c4-46cb-aeaf-f553682d79a9    53  Female         Spain
136   be14daac-e920-483b-9e35-cba65b3bfd92    46  Female         India
137   1c6b1ac6-1002-4b36-8fd5-1c10ae5b632c    23  Female        Mexico
138   d1ff9108-e92c-44de-b5ea-c529d1783957    41    Male        Mexico
139   b4bc9ecf-7216-4ca9-bc91-5d590ddd1a9d    14    Male        Canada
140   ed298fb4-3ea3-4c92-a538-7fe6fe7a7bb5    18  Female          Iran
141   5b49451a-0ed2-42c0-89f1-e5dbd4ee61da    18  Female         China
142   ab59cc4b-5dbd-44f2-ae12-29f41788ceda    33     NaN           USA
143   43c40cd4-b36f-45f5-b69d-1d6a8c4e152f    14  Female   South Korea
144   fcede627-64f9-47f3-a2fb-06e1601eb9f3    25    Male        Mexico
145   91febda3-377e-457b-9f1d-8f4970ede405    22    Male        Canada
146   0e90ac96-4cb4-4cdd-be24-dee5f09b553b    44    Male         China
147   5ca89fdb-c686-406e-94b4-6e6002ff1f6c    52    Male       Denmark
148   46defc98-35ab-4143-907b-2079fdee31ba    35  Female         Japan
149   1d400a74-33a2-4094-8066-674e04ce1a70    15  Female   Afghanistan
150   c703b6da-38c9-471a-b24d-d018211f9f85    13    Male     Australia
151   331deea7-19c1-4927-892b-76174d56ec49    29  Female         Spain
152   183a3fa8-6e20-4e1b-a691-7f7dcebe7a33    48    Male       Germany
153   2a783ac4-7027-4262-b320-c9149cffc55e    32    Male        Turkey
154   3fdb270f-8483-45fd-9ab4-db3052986187    14    Male   Switzerland
155   d8d662bd-4aa9-4cd7-86aa-1bc17f91294c    27    Male         Italy
156   a48782e4-26df-4f96-93cf-5e257242f1ed    20    Male        Brazil
157   b24d9feb-ba9d-43e7-ba75-f23bdfc550b3    53    Male        Canada
158   26eb8952-31d6-44a4-b20c-062176a5863c    22  Female         India
159   45aec45a-b3b8-4154-a53b-38cf145fffd5    16    Male         India
160   7c28ad05-8b95-4859-88ec-f00daaf02b99    28  Female        Turkey
161   2a88cfbc-0304-4d3c-beae-9a6537f9ccf4    16    Male           USA
162   6225ea4b-e767-4b86-98ee-ff16d5cc6553    43  Female   South Korea
163   9c00ee70-d6c0-48e7-ae8c-86624d8242d4    29  Female         Egypt
164   9d36db05-510d-4d8c-b7a9-4d2d9e5bb7c5    43    Male         India
165   bcb6e14f-1ff4-4d64-bf00-d41fd29961ad  <NA>  Female        Brazil
166   b99eb8c7-f6c9-4d78-95ee-c092b374e877    35    Male         Japan
167   c0b33c59-121b-4ecd-8afc-b15a56f05f98    24    Male        Sweden
168   6e93617a-0fcc-4fdf-90cd-4e62f1feea2a    23    Male     Australia
169   8a324a49-8484-48b1-91b2-a97c5371ab03    13    Male         India
170   608d9f0b-26ca-40ca-bef1-8028a610efd5    19    Male   Netherlands
171   37af1ed6-33b9-46ee-887a-38cce6c8f89a    32  Female        Turkey
172   7dc3d885-47b6-4ff1-bf91-610920fefb62    30     NaN   Afghanistan
173   5f79202e-0406-491b-989e-d2449e943c4d    37    Male         Spain
174   7fe571aa-451b-4fed-b1d8-6b976985d30a    51    Male            UK
175   bc42d13e-06b4-4ac5-aa4b-4909f201829a    33    Male         India
176   1bfc05b0-5c46-4652-a050-3623aa98c63d    39    Male    Bangladesh
177   a384e317-6490-4f5f-9042-db164b856a27    45    Male  Saudi Arabia
178   96cece19-9d64-48c0-8453-cd3cfc54b13f    45    Male         India
179   b79d286f-4d90-43bb-8f6e-f7fd319eadad    40    Male    Bangladesh
180   8c9b4eaa-d9fe-42ab-9a03-e0eb37d9bbfe    51  Female   South Korea
181   b64870a7-b26b-42f3-9e08-583d869ec2bc    27  Female   South Korea
182   bce6f198-360d-4ecc-ba91-63ec5f4428e7    52    Male         Italy
183   0a27824c-f44c-41d2-bbdb-a72f7e05976d    17    Male          Iran
184   fe5e6540-a6d4-4f52-8f6c-49f39a798753    30    Male        Mexico
185   f7ecc1c5-d64d-4f22-b389-f2447e756d0f    53  Female     Australia
186   0ac34a31-e5b0-450e-9b78-807f4dc920bd    36    Male   South Korea
187   9c90326e-28ba-4dbd-bf48-d182f5c5ec87    46    Male        Sweden
188   bd726fee-fde2-4063-8532-3f16aa8e2a56  <NA>    Male   Afghanistan
189   9de29aeb-075b-462d-9049-72133694847a    14  Female       Denmark
190   32e6555f-1157-483f-b9ed-be0696940fc8    49  Female         India
191   3e18d192-0991-475a-9fbc-ef448ba7df8e    41    Male         Italy
192   8dd3d210-13f7-4ec2-a2d7-924d7d3a1dd1    35     NaN   South Korea
193   2de4aa24-87fe-4fa8-928f-f2e8a2407cce    33    Male         India
194   b7f2effd-6c0b-4cfb-9116-a53b2828ecf7    49  Female    Bangladesh
195   0202a126-e63e-4a78-9ca2-f4ffef1d1558    35    Male         Italy
196   a18c92c3-5270-4abc-9147-238d3f08944d    29    Male        Norway
197   815cecaf-fce3-4d33-b308-97e563da3d9e    42    Male         Egypt
198   7585a97e-3b6b-4e77-80d2-265445a0aceb    52    Male        France
199   d3095600-2911-4658-a0e4-9b3e71ba0e40    15    Male   Netherlands
200   9e6fe49e-5f4e-421f-9de7-08c5745588a9    14     NaN        Brazil
201   a8ae7b9d-af5f-4384-b42c-368dc37e7e5c    19    Male        Norway
202   ba0a0643-db22-4441-a188-e509246a682b    31  Female     Sri Lanka
203   9f844184-9fcc-4ddf-948e-a8a06a79bf45    30    Male     Sri Lanka
204   1a4ab072-e221-42f5-9b79-6da7352e1f17    18    Male        Brazil
205   b86d25d2-b624-458a-a7ad-a3460c466e99    42    Male         Spain
206   950d5816-1db4-4107-86b1-b0eb93a8fdf7    14    Male       Germany
207   08a3aa8f-88cc-4f3f-a69c-5b002ad7aaad    43  Female         Italy
208   e035314c-dd1a-43f5-92c7-27fc090e7562    49    Male     Sri Lanka
209   bcf4d674-d9cc-4c41-b90c-f69bc332235d    52    Male   Afghanistan
210   f34384a2-7325-4713-a0d8-920daed8a3de    30  Female   Netherlands
211   c6a03f68-58b9-44a4-922f-4031ab1136a7    31  Female        Mexico
212   18bb4c37-a9cb-4706-9210-57011be1c66f    21  Female         Italy
213   3b8761c1-27d9-4957-bd5d-aaf09f5409ff    47    Male     Sri Lanka
214   2b5f9d97-d98a-48ff-9fe0-42894333b36a    16    Male   South Korea
215   c6a5c9dc-ed1e-4f35-a000-b6e7b2c6ef70    41  Female        Mexico
216   82edc8a5-83c2-4894-807d-234c912e5477    45  Female  Saudi Arabia
217   b5810a9e-6ff2-476f-96c5-4b285cebbac1    22    Male        Mexico
218   e5689efe-ffba-4c62-8e4f-0d2da3c79dd0    19    Male       Germany
219   81cab772-c5d5-46a3-8c45-2ff02a9d21d5    37  Female     Sri Lanka
220   2afe4941-c293-4068-83dd-2bc72b1b7123    32    Male    Bangladesh
221   b22003d2-4698-4c16-a5b3-eed4a494d0a9    17  Female         Japan
222   ee1a179f-ecb3-4dd9-9b59-11823faf46e4    20    Male        Norway
223   fcb50b3c-7efa-48c2-bb91-228a8e401b89    40  Female        Mexico
224   8a91fa57-d4e4-43e9-8684-456b108237d6    51    Male   South Korea
225   20865a0d-733a-4d1d-9997-02e67f350932    20  Female          Iran
226   c4fedcdb-0ed7-47b6-ac7e-5fbcb2421fb4    29  Female        Norway
227   ba478a10-df2b-4c63-88c7-185f740e3738    20  Female   Afghanistan
228   21923a3e-6de2-44f2-8839-c9e61b46765a    13    Male           USA
229   24a5635b-34f2-436d-b9e6-4d155dcecee1    30  Female     Sri Lanka
230   f0748d5b-661c-4f2b-b236-2dd399809aab    38  Female     Australia
231   b78c392f-b9aa-4366-b712-c7e84bdc6c35    43  Female    Bangladesh
232   6f16f229-3ecf-4618-b571-c1e902734af3    14  Female           NaN
233   583599e7-193b-4019-9e03-27e687d5bb34    25    Male   Netherlands
234   49656b72-f958-4dca-84db-ce772059a6f1    26  Female       Germany
235   489b35f4-7612-4d31-a6cb-1bb127b88ae3    47  Female          Iran
236   9cd3e13b-de09-49d1-9d6a-0f35e5a66523    25  Female        Turkey
237   9f653d6c-0ee6-4390-a238-ed39024348f4    15  Female         Spain
238   fd116d08-e23f-495f-a323-44d6d9a21a8e    14    Male         Japan
239   158aeb25-5f92-45c3-ae37-8b44b5fa5172    17  Female        Norway
240   6c7b3db2-6b53-481c-897e-358a7e310323    40    Male   South Korea
241   3dd22990-c352-491c-9d18-3b40cf762492    16    Male         Spain
242   7377eeb5-20da-42ac-8ef3-a2d79e9a367d    18    Male       Denmark
243   c0f58ea1-0d56-4bae-a379-77833f58e1ec    36    Male          Iran
244   2df6aca1-4c6a-4e77-8dff-fa5fc8609726    46  Female           USA
245   0e1d1d07-c427-4e44-a015-ed199199d982    39  Female        Mexico
246   c2a5f183-390b-40f3-b9fd-1a6acd64e968    13    Male         India
247   f9e77e0f-0e19-4609-b11a-128844cf34a9    19  Female         Egypt
248   d3d71ba1-6331-482b-ab2f-0f0810e3e310    43    Male     Australia
249   5575ca75-b875-42be-adc9-f068778ea73d    29    Male         Japan
250   c7ac31a3-cbc2-464a-a902-0cc67b9ddb60    51    Male        Brazil
251   28774c61-a933-4ae9-8503-cf5967e56d5c    21    Male         Egypt
252   fbd65117-f7c5-47b9-9162-7d3e643e79cd    19    Male   South Korea
253   868ab631-3057-4979-b233-5b307d20e475    21  Female     Sri Lanka
254   1bf14ea6-aab2-4d68-be04-832f9515b183    49  Female     Australia
255   836d7b01-1b32-438a-9e56-514a6494d848    40    Male        Canada
256   6d7c2868-79d4-40f5-94cc-c8300d6a409e    19  Female   South Korea
257   d39a96e7-f66c-4a1d-9073-c8f05dd315c5    19    Male        Sweden
258   39b4a4fb-a36b-4dc3-9c7a-e7f2ab21d02d    21  Female        Canada
259   83b88cd3-1b65-41a8-a3e6-1532085fda74    34    Male            UK
260   8e26c709-34ab-4db0-8d1b-80eddcc0aca7    28    Male   Netherlands
261   a8bf6828-3adb-41b0-8232-153737754604    47  Female        Turkey
262   b2afcd56-2fcd-4e09-ba68-547125cdec1a    36  Female           USA
263   4dc9a8b8-e379-4d24-a667-f34f9729852f    42    Male   Afghanistan
264   9ddd7102-a354-4612-9456-d9946e6583ad    22    Male       Germany
265   74d3c6b8-0f64-4a00-b021-39403c95c751    24    Male        Mexico
266   c7aacb9b-7b33-479c-aae9-ecd0aaddd50b    18    Male            UK
267   75a44ecd-8ba7-4833-8d98-5444adf1296c    52    Male        Russia
268   95ddad04-3639-4e5c-b098-63ec5f39cc6e    13    Male     Sri Lanka
269   c5e10c4c-16ff-4b8a-8014-3d74076546b1    45    Male           USA
270   e953bfe5-8b5f-407b-bb41-26b45ac4e752    49  Female            UK
271   1b8e312d-a914-4007-8f8a-6fc4d1754e85    30    Male       Germany
272   0778cc79-09e4-417a-b022-ccbf69d7865d    42  Female        Norway
273   bc331aeb-abf6-4cda-837a-fe0ee76d5df7    20  Female         India
274   f0b60984-56ea-4a30-8058-adef47617cdf    33  Female        Mexico
275   d3fdd03d-cb34-4127-a0e9-cb923101283d    25   Other   Switzerland
276   886b9aca-5d31-4065-a308-ddf1140fe728    21    Male       Denmark
277   0d15b643-977d-4ec4-9599-7c59b5ee3e73  <NA>  Female        Mexico
278   a730f213-444f-460d-b28d-8ce751973bd9    49    Male        Turkey
279   a61e91e8-43a9-40b9-964e-c354110f0e43    29   Other       Denmark

In [26]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         3024 non-null   object
 1   Age                            2964 non-null   float64
 2   Gender                         2964 non-null   object
 3   Country                        2964 non-null   object
 4   Device                         2964 non-null   object
 5   GameGenre                      2964 non-null   object
 6   SessionCount                   3024 non-null   int64
 7   AverageSessionLength           3024 non-null   float64
 8   SpendingSegment                3024 non-null   object
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   float64
 11  PaymentMethod                  2888 non-null   object
 12  LastPurchaseDate               2888 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 307.3+ KB

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         3024 non-null   object
 1   Age                            2964 non-null   Int64
 2   Gender                         2964 non-null   object
 3   Country                        2964 non-null   object
 4   Device                         2964 non-null   object
 5   GameGenre                      2964 non-null   category
 6   SessionCount                   3024 non-null   int64
 7   AverageSessionLength           3024 non-null   float64
 8   SpendingSegment                3024 non-null   object
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   Int64
 11  PaymentMethod                  2888 non-null   object
 12  LastPurchaseDate               2888 non-null   datetime64[ns]
dtypes: Int64(2), category(1), datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 293.1+ KB

### Converting appropriate columns to optimized data types reduced memory usage and improved overall efficiency.

# Data Consistency Checks

In [30]:
df['Age'].describe()

count       2964.0
mean     33.533738
std      11.992258
min           13.0
25%           23.0
50%           33.0
75%           44.0
max           54.0
Name: Age, dtype: Float64

In [31]:
df[(df['Age'] < 0) | (df['Age'] > 100)]

Empty DataFrame
Columns: [UserID, Age, Gender, Country, Device, GameGenre, SessionCount, AverageSessionLength, SpendingSegment, InAppPurchaseAmount, FirstPurchaseDaysAfterInstall, PaymentMethod, LastPurchaseDate]
Index: []

In [32]:
df['SessionCount'].describe()

count    3024.000000
mean       10.074735
std         3.115863
min         1.000000
25%         8.000000
50%        10.000000
75%        12.000000
max        22.000000
Name: SessionCount, dtype: float64

In [33]:
df[df['SessionCount'] < 0]

Empty DataFrame
Columns: [UserID, Age, Gender, Country, Device, GameGenre, SessionCount, AverageSessionLength, SpendingSegment, InAppPurchaseAmount, FirstPurchaseDaysAfterInstall, PaymentMethod, LastPurchaseDate]
Index: []

In [34]:
df['AverageSessionLength'].describe()

count    3024.000000
mean       20.073978
std         8.585208
min         5.010000
25%        12.680000
50%        20.315000
75%        27.420000
max        34.990000
Name: AverageSessionLength, dtype: float64

In [35]:
df[df['AverageSessionLength'] < 0]

Empty DataFrame
Columns: [UserID, Age, Gender, Country, Device, GameGenre, SessionCount, AverageSessionLength, SpendingSegment, InAppPurchaseAmount, FirstPurchaseDaysAfterInstall, PaymentMethod, LastPurchaseDate]
Index: []

In [36]:
df['InAppPurchaseAmount'].describe()

count    2888.000000
mean      102.582864
std       454.339708
min         0.000000
25%         5.987500
50%        11.975000
75%        17.762500
max      4964.450000
Name: InAppPurchaseAmount, dtype: float64

In [37]:
df[df['InAppPurchaseAmount'] < 0]

Empty DataFrame
Columns: [UserID, Age, Gender, Country, Device, GameGenre, SessionCount, AverageSessionLength, SpendingSegment, InAppPurchaseAmount, FirstPurchaseDaysAfterInstall, PaymentMethod, LastPurchaseDate]
Index: []

In [38]:
df['FirstPurchaseDaysAfterInstall'].describe()

count       2888.0
mean     15.384003
std       8.946191
min            0.0
25%            8.0
50%           16.0
75%           23.0
max           30.0
Name: FirstPurchaseDaysAfterInstall, dtype: Float64

In [39]:
df[df['FirstPurchaseDaysAfterInstall'] < 0]

Empty DataFrame
Columns: [UserID, Age, Gender, Country, Device, GameGenre, SessionCount, AverageSessionLength, SpendingSegment, InAppPurchaseAmount, FirstPurchaseDaysAfterInstall, PaymentMethod, LastPurchaseDate]
Index: []

In [40]:
df['PaymentMethod'].value_counts(dropna=False)

PaymentMethod
Debit Card         433
Google Pay         431
Gift Card          422
Carrier Billing    417
Credit Card        410
Paypal             401
Apple Pay          374
NaN                136
Name: count, dtype: int64

In [41]:
df['SpendingSegment'].value_counts(dropna=False)

SpendingSegment
Minnow     2544
Dolphin     412
Whale        68
Name: count, dtype: int64

In [42]:
df['Gender'].value_counts(dropna=False)

Gender
Male      1810
Female    1098
NaN         60
Other       56
Name: count, dtype: int64

In [43]:
df['Device'].value_counts(dropna=False)

Device
Android    1738
iOS        1226
NaN          60
Name: count, dtype: int64

In [44]:
df['GameGenre'].value_counts(dropna=False)

GameGenre
Sandbox          219
Simulation       219
Sports           217
Casual           209
Puzzle           206
Card             202
MMORPG           198
Strategy         198
Role Playing     193
Action RPG       191
Racing           191
Battle Royale    189
Fighting         181
MOBA             181
Adventure        170
NaN               60
Name: count, dtype: int64

In [45]:
clean_df = df.copy()

In [46]:
clean_df.to_csv('clean_mobile_game_dataset.csv', index=False) #Saving the cleaned csv

In [47]:
clean_df

                                    UserID   Age  Gender       Country  \
0     c9889ab0-9cfc-4a75-acd9-5eab1df0015c    49    Male        Norway
1     7c9e413c-ecca-45f2-a780-2826a07952a2    15    Male   Switzerland
2     fd61e419-1a92-4f43-a8c7-135842ad328a    23    Male         China
3     bdb7f6d1-ff9a-468c-afe7-43f32a94293e    31    Male        Mexico
4     aa7eec14-4846-47b9-b879-9c98038cda04    37  Female         India
5     992232c1-a563-4986-aa8b-b70d687d374f    38  Female         China
6     702bafd0-9a08-4269-801e-faf32f9f3ca5    20  Female         Italy
7     fc470ea9-111f-4637-a9ff-7162d81e2ec3    34  Female       Denmark
8     9b2efc1e-cd4b-48ab-b893-438d57855efa    38    Male         Japan
9     25723b60-ea5b-4aff-9f23-97fdf5e98c58    46    Male        Russia
10    2bb44e49-c28d-4023-ac75-33d92cb77870    29    Male   Switzerland
11    a516f724-6b0f-438c-b20b-59f5f35ab06a    31    Male        Sweden
12    f72780cf-bccf-4ae5-8c12-09ee9d511322    30  Female     Australia
13    659f30ff-48f1-4e76-8f82-312d98e1ba76    24    Male        Turkey
14    34c56aa2-33c0-40c0-af9b-6c5b45929851    21    Male   South Korea
15    ae1ccfa2-8967-4981-be8f-a5c3b0f9f394    35    Male   Switzerland
16    bb0cf750-9fd2-4329-acc8-dc40dedaff3d    37  Female         Japan
17    cf1326be-4810-4b4d-bbc9-ff7b8c22d5ab    45    Male  Saudi Arabia
18    784fa153-301d-4286-adf5-3459e04e8a97    14  Female     Sri Lanka
19    9f1bd962-1ace-403e-aabb-eda9bd08e999    47  Female        Sweden
20    2cd9ff69-2a0d-4df7-82d5-400d609f66f5    35  Female        Mexico
21    d17030c2-e861-4028-aa03-23b18d239a40    14    Male         Japan
22    9b7c844f-1891-49da-a71d-b0b2719deda5    21    Male        Canada
23    2bf7d319-fba5-4d64-9187-358045a4ed40    54    Male        Canada
24    bab46c87-b7a7-4e1c-b56f-d1c8d2897733    47    Male       Denmark
25    902744c6-0620-47d6-92aa-b1d719b1d50f    52    Male     Sri Lanka
26    38041854-4fcc-41f7-a662-cf466afce86f    25    Male         Italy
27    cc7fffae-d126-4f3b-bbc4-c81213b6bf69    51    Male         India
28    03e7dc1d-dfe5-4677-aff4-239b6a60ad7c    18    Male   Switzerland
29    0d4f2cd8-6cee-4133-8cb2-435a0f6d19ef  <NA>  Female        Russia
30    1afae40f-9b90-4710-a024-13d1d2b4266e    32    Male        France
31    2868c7dc-a4bc-4143-8256-334e29ec7458    54  Female           USA
32    8b27e55c-6841-4e55-ad1d-a953319e7839    34  Female           NaN
33    51632073-5433-48ef-a95f-a519029bb068    30  Female            UK
34    caddf020-37f9-42c6-b9d3-cf256901e2a9    31  Female   Netherlands
35    3d303a23-7484-45ec-ac02-e7e533b6b1f3    43    Male        Canada
36    c6301a66-20d3-4bd7-9ba5-664de4f1814b    49    Male   South Korea
37    9df52d99-a9d8-45d4-804d-d0288f9c88f2    54    Male        Norway
38    078c53b3-d2f8-4587-a779-d66661ed6351    38    Male        Norway
39    609ec77e-7c64-4486-a77d-da39f5e21576    17    Male  Saudi Arabia
40    b6208d5f-f05f-4b64-a9be-f0e3262c3952    19  Female           NaN
41    cb88b1cf-7ccc-4c4f-98b6-d6906c1bbb20    38    Male        Mexico
42    05ef5257-cb10-41a7-93be-616389d660f2    34    Male     Australia
43    daa87ce2-9524-437b-96f5-d862e44ba2a6    20  Female         Egypt
44    2059ae35-b1ea-4c2a-bbce-b89233c30938    32  Female         India
45    11826044-01a7-4201-af8a-5a93cc6a9b38    16  Female         Spain
46    69f06b32-f62f-4cf8-b5f2-c33c16ec646c    36    Male            UK
47    533679ef-f6a5-450d-858b-92a7a2e10de4    48  Female        France
48    5e12bef2-00c7-4634-b3b2-b0926e9cb9fc    35    Male        Brazil
49    f60f1c9a-d523-4648-a09c-7928e79fb2be    50    Male            UK
50    9c3598c6-6cd4-4da2-81ed-a8053987aa80    33  Female         Japan
51    e29badd2-8522-4287-bd03-a80fe9b71548    44  Female        Canada
52    2f9b59a8-8fa4-48cf-abec-3f3dd76aaf86    36  Female   Switzerland
53    536b79a9-29ac-4636-ae84-f4caff4b4ba0    29    Male           USA
54    d7b8a563-a467-4b0a-ad49-476e778e2417    25  Female        Sweden
55    3941a6e4-c925-4016-9701-99dacd2b8c81    52    Male    Bangladesh
56    b5084cbd-e884-4626-987a-91b4d1506d0d    18    Male         Spain
57    26cead3d-1110-410d-ab56-6e4c54c2d268    18    Male         Japan
58    dc8284d9-82a4-46b2-b871-50348b048411    17  Female         India
59    b5c61dc0-138d-4d49-ae4a-c4ca75787cb2    49    Male   Afghanistan
60    831776e9-a34f-4ea7-a68c-d453907cc5f2    40  Female         Japan
61    402ee755-ca98-477f-8c8d-a54fc4fa9c29    26    Male     Australia
62    b8515403-f053-45b6-9855-735e939cbaaa    50    Male            UK
63    75c92497-1ce3-4fff-8390-7fd40ccdcdc0    47    Male        Canada
64    f995f3e3-ffc4-4eed-abd3-c23ca495f86a    44    Male        Norway
65    4b416d1d-bd9e-4bfc-b4c9-0597a983fffd    13    Male     Australia
66    bb33b2f4-a9f7-49f0-893a-1e37582656d8    33    Male  Saudi Arabia
67    6dcd7ef4-f90d-4745-b0d7-514c8d318ee6    24  Female    Bangladesh
68    c89433ee-4f4f-42f3-98e6-8ffa5c82a199    29  Female       Denmark
69    a6164e91-512e-4fb3-9fd7-e1b81ab01306    52    Male        Turkey
70    bbe10e54-9d0f-4ded-b144-9540adaa29ae    38  Female         Egypt
71    f3b619e3-454a-4afa-8727-eb260a7cf161    26    Male   Afghanistan
72    a8eb7f0a-2b5b-4e33-b735-bdbcd167e6c9    50  Female        Russia
73    491dd37f-368b-4170-a53e-bb50bd2cf501    42  Female        France
74    a2cff92e-52de-4e63-8318-4dfb42c4a445    20    Male     Australia
75    5de124a0-1cb3-4486-87cb-9699cda32a6c    19    Male        Brazil
76    8bfa625a-9651-4818-a1a2-e1cc6985f12c    31  Female         India
77    a125ceb7-abc0-4e40-a418-2023a5c38edb    30    Male           USA
78    d88da455-eacb-4fc0-b7d8-9ee22f1c0ffa    18    Male  Saudi Arabia
79    47b6299d-8f0e-4cb3-8275-f8bc157318c8    21    Male        Canada
80    9e57ae3d-1a32-4913-b522-8b576f672731    37   Other        Mexico
81    55b14ef0-9383-48b5-9e88-b5814331b23d  <NA>  Female            UK
82    3e38f13d-0869-44c3-aec1-f204f7a370ef    33    Male        Turkey
83    5f20a679-6f98-4bbd-b463-819edc54b2b9    28    Male   Netherlands
84    523abcfa-4d38-4a89-b5f5-ce5e4f215fcf  <NA>    Male    Bangladesh
85    bb8e3213-005c-4565-81a3-27fdbf103c57    39    Male         Japan
86    d5913936-3c9e-4b38-96ed-6d151d5f3e95    51    Male   Switzerland
87    6c2a5488-7147-4d3b-b05d-73991b8c8730    51    Male        Turkey
88    cd5a9e40-7add-48fb-8adf-99796d5072fb    50    Male       Denmark
89    f8f073c4-5291-4675-a58f-d178815d0d96    22    Male         Egypt
90    713e8104-54bd-470c-a778-3fbc4a9290a0    24    Male         Spain
91    e679e2e0-b0b0-4522-96d0-504f0e7cbf06    25  Female       Germany
92    80c3199d-e975-4ccd-85ef-13c59aa1f805    28    Male        Turkey
93    9d7e9a20-197d-4104-9886-808d8b9afe03    23  Female   Switzerland
94    a6eccba4-c776-4d6d-97b0-facfb3198010    39  Female          Iran
95    e02f17d6-dec7-440c-ad82-3c5b78120050    20  Female         India
96    96719446-f2bc-47cf-83e5-3f74da1ea9e4    36    Male            UK
97    f5bcac4c-23dc-41aa-86f8-6a7e62262f89    28  Female   South Korea
98    ba8e2c67-c8d7-4eea-9140-de8b5a8c7408    53    Male          Iran
99    24cbe32b-e245-4402-a633-a4bb912b6c53    26  Female          Iran
100   7274e19d-b3cc-4e0c-9260-4fd47a7355f0    17  Female         Italy
101   f0606a81-b49e-42ec-8439-5a2c8537ba31    13    Male   Netherlands
102   1a1197fb-e7c7-498f-8f62-740898e0ad28    38    Male    Bangladesh
103   36fffb0c-b111-40a3-9d01-b960914e05c3    49    Male         China
104   2712e660-4d07-4b97-ae2f-f260de26762f    49    Male   Netherlands
105   5f40e5c4-5bdf-49cd-a1c5-0db095391e26    29  Female           NaN
106   a1569884-f0ba-4715-9625-79bd34e31a29    33    Male  Saudi Arabia
107   1bd97852-263c-43ed-afbd-515619bb6713    27    Male         Spain
108   44f04607-d70e-43e7-9946-cfccd2c506ff    26    Male         Spain
109   6a3e7755-15d2-4261-b6b9-2040975ba87c    24  Female            UK
110   765f67bd-0006-4e9a-b3b1-d017e9e42fa3    22  Female        Brazil
111   65c9070d-a1dc-46a1-8041-f1ff52f0b476    44  Female   South Korea
112   63c439e3-2274-4107-9dc5-e93cd5325423    24  Female     Australia
113   ea67c7b3-f672-4d1f-a87c-b6ad687805d7    52    Male        Mexico
114   8840c167-29ab-4573-ba75-be52c1b9e508    20    Male   Afghanistan
115   e9eadb83-df6f-4f35-a218-b11768a69681    40    Male        Norway
116   1d725650-a2de-4bde-b2c1-0a2116831067    19    Male         China
117   d4cb7f92-952d-4528-b4bb-96d4a9bd038a    37    Male         Italy
118   bdac696e-6890-437b-97cc-6979587048bd    36    Male         Egypt
119   3e5c7e39-a2e3-4e94-a2fb-210453694387    51    Male       Germany
120   8bbdc323-6d6a-47f7-9ef9-0ed2d2d6cb0a    26  Female         Italy
121   a6fa3862-4789-466e-8f29-f08d754e9e8c    34    Male         Spain
122   1f582143-b515-493b-86c9-8a36fedffabe    25  Female           USA
123   40462d77-d324-497b-80f8-f94c9bcfb5ef    27    Male    Bangladesh
124   f952dd17-61b1-4f47-a01f-19e66d0b84dc    40  Female        Sweden
125   b896ef32-5e12-4eed-a8a3-b144188deb8f    42     NaN         China
126   c1833346-8b2d-4775-bdb9-de5e417013e9    50    Male        France
127   92ef0133-13ca-4f43-bedb-bf91815bf36f    43    Male     Sri Lanka
128   2da8404d-b63d-4c9c-a0f4-35aff413d004    26    Male         India
129   b4ede4a8-eea4-4416-a89a-5a92a700a1f2    36    Male         India
130   b23912e7-0c77-4bb1-a4c8-3c6937a6b24f    36    Male         India
131   d6015577-c9c0-4570-af35-db924ca0bdc8    52    Male         Spain
132   c97c7aeb-5d60-4f9c-9e55-cdce38c7e8e1    43    Male        Mexico
133   ed7b7b9c-22a6-4558-8f8a-8a4556b2e093    13  Female   South Korea
134   f7668438-a3c8-4a02-bd33-6840b93697de    18  Female    Bangladesh
135   247a935c-a5c4-46cb-aeaf-f553682d79a9    53  Female         Spain
136   be14daac-e920-483b-9e35-cba65b3bfd92    46  Female         India
137   1c6b1ac6-1002-4b36-8fd5-1c10ae5b632c    23  Female        Mexico
138   d1ff9108-e92c-44de-b5ea-c529d1783957    41    Male        Mexico
139   b4bc9ecf-7216-4ca9-bc91-5d590ddd1a9d    14    Male        Canada
140   ed298fb4-3ea3-4c92-a538-7fe6fe7a7bb5    18  Female          Iran
141   5b49451a-0ed2-42c0-89f1-e5dbd4ee61da    18  Female         China
142   ab59cc4b-5dbd-44f2-ae12-29f41788ceda    33     NaN           USA
143   43c40cd4-b36f-45f5-b69d-1d6a8c4e152f    14  Female   South Korea
144   fcede627-64f9-47f3-a2fb-06e1601eb9f3    25    Male        Mexico
145   91febda3-377e-457b-9f1d-8f4970ede405    22    Male        Canada
146   0e90ac96-4cb4-4cdd-be24-dee5f09b553b    44    Male         China
147   5ca89fdb-c686-406e-94b4-6e6002ff1f6c    52    Male       Denmark
148   46defc98-35ab-4143-907b-2079fdee31ba    35  Female         Japan
149   1d400a74-33a2-4094-8066-674e04ce1a70    15  Female   Afghanistan
150   c703b6da-38c9-471a-b24d-d018211f9f85    13    Male     Australia
151   331deea7-19c1-4927-892b-76174d56ec49    29  Female         Spain
152   183a3fa8-6e20-4e1b-a691-7f7dcebe7a33    48    Male       Germany
153   2a783ac4-7027-4262-b320-c9149cffc55e    32    Male        Turkey
154   3fdb270f-8483-45fd-9ab4-db3052986187    14    Male   Switzerland
155   d8d662bd-4aa9-4cd7-86aa-1bc17f91294c    27    Male         Italy
156   a48782e4-26df-4f96-93cf-5e257242f1ed    20    Male        Brazil
157   b24d9feb-ba9d-43e7-ba75-f23bdfc550b3    53    Male        Canada
158   26eb8952-31d6-44a4-b20c-062176a5863c    22  Female         India
159   45aec45a-b3b8-4154-a53b-38cf145fffd5    16    Male         India
160   7c28ad05-8b95-4859-88ec-f00daaf02b99    28  Female        Turkey
161   2a88cfbc-0304-4d3c-beae-9a6537f9ccf4    16    Male           USA
162   6225ea4b-e767-4b86-98ee-ff16d5cc6553    43  Female   South Korea
163   9c00ee70-d6c0-48e7-ae8c-86624d8242d4    29  Female         Egypt
164   9d36db05-510d-4d8c-b7a9-4d2d9e5bb7c5    43    Male         India
165   bcb6e14f-1ff4-4d64-bf00-d41fd29961ad  <NA>  Female        Brazil
166   b99eb8c7-f6c9-4d78-95ee-c092b374e877    35    Male         Japan
167   c0b33c59-121b-4ecd-8afc-b15a56f05f98    24    Male        Sweden
168   6e93617a-0fcc-4fdf-90cd-4e62f1feea2a    23    Male     Australia
169   8a324a49-8484-48b1-91b2-a97c5371ab03    13    Male         India
170   608d9f0b-26ca-40ca-bef1-8028a610efd5    19    Male   Netherlands
171   37af1ed6-33b9-46ee-887a-38cce6c8f89a    32  Female        Turkey
172   7dc3d885-47b6-4ff1-bf91-610920fefb62    30     NaN   Afghanistan
173   5f79202e-0406-491b-989e-d2449e943c4d    37    Male         Spain
174   7fe571aa-451b-4fed-b1d8-6b976985d30a    51    Male            UK
175   bc42d13e-06b4-4ac5-aa4b-4909f201829a    33    Male         India
176   1bfc05b0-5c46-4652-a050-3623aa98c63d    39    Male    Bangladesh
177   a384e317-6490-4f5f-9042-db164b856a27    45    Male  Saudi Arabia
178   96cece19-9d64-48c0-8453-cd3cfc54b13f    45    Male         India
179   b79d286f-4d90-43bb-8f6e-f7fd319eadad    40    Male    Bangladesh
180   8c9b4eaa-d9fe-42ab-9a03-e0eb37d9bbfe    51  Female   South Korea
181   b64870a7-b26b-42f3-9e08-583d869ec2bc    27  Female   South Korea
182   bce6f198-360d-4ecc-ba91-63ec5f4428e7    52    Male         Italy
183   0a27824c-f44c-41d2-bbdb-a72f7e05976d    17    Male          Iran
184   fe5e6540-a6d4-4f52-8f6c-49f39a798753    30    Male        Mexico
185   f7ecc1c5-d64d-4f22-b389-f2447e756d0f    53  Female     Australia
186   0ac34a31-e5b0-450e-9b78-807f4dc920bd    36    Male   South Korea
187   9c90326e-28ba-4dbd-bf48-d182f5c5ec87    46    Male        Sweden
188   bd726fee-fde2-4063-8532-3f16aa8e2a56  <NA>    Male   Afghanistan
189   9de29aeb-075b-462d-9049-72133694847a    14  Female       Denmark
190   32e6555f-1157-483f-b9ed-be0696940fc8    49  Female         India
191   3e18d192-0991-475a-9fbc-ef448ba7df8e    41    Male         Italy
192   8dd3d210-13f7-4ec2-a2d7-924d7d3a1dd1    35     NaN   South Korea
193   2de4aa24-87fe-4fa8-928f-f2e8a2407cce    33    Male         India
194   b7f2effd-6c0b-4cfb-9116-a53b2828ecf7    49  Female    Bangladesh
195   0202a126-e63e-4a78-9ca2-f4ffef1d1558    35    Male         Italy
196   a18c92c3-5270-4abc-9147-238d3f08944d    29    Male        Norway
197   815cecaf-fce3-4d33-b308-97e563da3d9e    42    Male         Egypt
198   7585a97e-3b6b-4e77-80d2-265445a0aceb    52    Male        France
199   d3095600-2911-4658-a0e4-9b3e71ba0e40    15    Male   Netherlands
200   9e6fe49e-5f4e-421f-9de7-08c5745588a9    14     NaN        Brazil
201   a8ae7b9d-af5f-4384-b42c-368dc37e7e5c    19    Male        Norway
202   ba0a0643-db22-4441-a188-e509246a682b    31  Female     Sri Lanka
203   9f844184-9fcc-4ddf-948e-a8a06a79bf45    30    Male     Sri Lanka
204   1a4ab072-e221-42f5-9b79-6da7352e1f17    18    Male        Brazil
205   b86d25d2-b624-458a-a7ad-a3460c466e99    42    Male         Spain
206   950d5816-1db4-4107-86b1-b0eb93a8fdf7    14    Male       Germany
207   08a3aa8f-88cc-4f3f-a69c-5b002ad7aaad    43  Female         Italy
208   e035314c-dd1a-43f5-92c7-27fc090e7562    49    Male     Sri Lanka
209   bcf4d674-d9cc-4c41-b90c-f69bc332235d    52    Male   Afghanistan
210   f34384a2-7325-4713-a0d8-920daed8a3de    30  Female   Netherlands
211   c6a03f68-58b9-44a4-922f-4031ab1136a7    31  Female        Mexico
212   18bb4c37-a9cb-4706-9210-57011be1c66f    21  Female         Italy
213   3b8761c1-27d9-4957-bd5d-aaf09f5409ff    47    Male     Sri Lanka
214   2b5f9d97-d98a-48ff-9fe0-42894333b36a    16    Male   South Korea
215   c6a5c9dc-ed1e-4f35-a000-b6e7b2c6ef70    41  Female        Mexico
216   82edc8a5-83c2-4894-807d-234c912e5477    45  Female  Saudi Arabia
217   b5810a9e-6ff2-476f-96c5-4b285cebbac1    22    Male        Mexico
218   e5689efe-ffba-4c62-8e4f-0d2da3c79dd0    19    Male       Germany
219   81cab772-c5d5-46a3-8c45-2ff02a9d21d5    37  Female     Sri Lanka
220   2afe4941-c293-4068-83dd-2bc72b1b7123    32    Male    Bangladesh
221   b22003d2-4698-4c16-a5b3-eed4a494d0a9    17  Female         Japan
222   ee1a179f-ecb3-4dd9-9b59-11823faf46e4    20    Male        Norway
223   fcb50b3c-7efa-48c2-bb91-228a8e401b89    40  Female        Mexico
224   8a91fa57-d4e4-43e9-8684-456b108237d6    51    Male   South Korea
225   20865a0d-733a-4d1d-9997-02e67f350932    20  Female          Iran
226   c4fedcdb-0ed7-47b6-ac7e-5fbcb2421fb4    29  Female        Norway
227   ba478a10-df2b-4c63-88c7-185f740e3738    20  Female   Afghanistan
228   21923a3e-6de2-44f2-8839-c9e61b46765a    13    Male           USA
229   24a5635b-34f2-436d-b9e6-4d155dcecee1    30  Female     Sri Lanka
230   f0748d5b-661c-4f2b-b236-2dd399809aab    38  Female     Australia
231   b78c392f-b9aa-4366-b712-c7e84bdc6c35    43  Female    Bangladesh
232   6f16f229-3ecf-4618-b571-c1e902734af3    14  Female           NaN
233   583599e7-193b-4019-9e03-27e687d5bb34    25    Male   Netherlands
234   49656b72-f958-4dca-84db-ce772059a6f1    26  Female       Germany
235   489b35f4-7612-4d31-a6cb-1bb127b88ae3    47  Female          Iran
236   9cd3e13b-de09-49d1-9d6a-0f35e5a66523    25  Female        Turkey
237   9f653d6c-0ee6-4390-a238-ed39024348f4    15  Female         Spain
238   fd116d08-e23f-495f-a323-44d6d9a21a8e    14    Male         Japan
239   158aeb25-5f92-45c3-ae37-8b44b5fa5172    17  Female        Norway
240   6c7b3db2-6b53-481c-897e-358a7e310323    40    Male   South Korea
241   3dd22990-c352-491c-9d18-3b40cf762492    16    Male         Spain
242   7377eeb5-20da-42ac-8ef3-a2d79e9a367d    18    Male       Denmark
243   c0f58ea1-0d56-4bae-a379-77833f58e1ec    36    Male          Iran
244   2df6aca1-4c6a-4e77-8dff-fa5fc8609726    46  Female           USA
245   0e1d1d07-c427-4e44-a015-ed199199d982    39  Female        Mexico
246   c2a5f183-390b-40f3-b9fd-1a6acd64e968    13    Male         India
247   f9e77e0f-0e19-4609-b11a-128844cf34a9    19  Female         Egypt
248   d3d71ba1-6331-482b-ab2f-0f0810e3e310    43    Male     Australia
249   5575ca75-b875-42be-adc9-f068778ea73d    29    Male         Japan
250   c7ac31a3-cbc2-464a-a902-0cc67b9ddb60    51    Male        Brazil
251   28774c61-a933-4ae9-8503-cf5967e56d5c    21    Male         Egypt
252   fbd65117-f7c5-47b9-9162-7d3e643e79cd    19    Male   South Korea
253   868ab631-3057-4979-b233-5b307d20e475    21  Female     Sri Lanka
254   1bf14ea6-aab2-4d68-be04-832f9515b183    49  Female     Australia
255   836d7b01-1b32-438a-9e56-514a6494d848    40    Male        Canada
256   6d7c2868-79d4-40f5-94cc-c8300d6a409e    19  Female   South Korea
257   d39a96e7-f66c-4a1d-9073-c8f05dd315c5    19    Male        Sweden
258   39b4a4fb-a36b-4dc3-9c7a-e7f2ab21d02d    21  Female        Canada
259   83b88cd3-1b65-41a8-a3e6-1532085fda74    34    Male            UK
260   8e26c709-34ab-4db0-8d1b-80eddcc0aca7    28    Male   Netherlands
261   a8bf6828-3adb-41b0-8232-153737754604    47  Female        Turkey
262   b2afcd56-2fcd-4e09-ba68-547125cdec1a    36  Female           USA
263   4dc9a8b8-e379-4d24-a667-f34f9729852f    42    Male   Afghanistan
264   9ddd7102-a354-4612-9456-d9946e6583ad    22    Male       Germany
265   74d3c6b8-0f64-4a00-b021-39403c95c751    24    Male        Mexico
266   c7aacb9b-7b33-479c-aae9-ecd0aaddd50b    18    Male            UK
267   75a44ecd-8ba7-4833-8d98-5444adf1296c    52    Male        Russia
268   95ddad04-3639-4e5c-b098-63ec5f39cc6e    13    Male     Sri Lanka
269   c5e10c4c-16ff-4b8a-8014-3d74076546b1    45    Male           USA
270   e953bfe5-8b5f-407b-bb41-26b45ac4e752    49  Female            UK
271   1b8e312d-a914-4007-8f8a-6fc4d1754e85    30    Male       Germany
272   0778cc79-09e4-417a-b022-ccbf69d7865d    42  Female        Norway
273   bc331aeb-abf6-4cda-837a-fe0ee76d5df7    20  Female         India
274   f0b60984-56ea-4a30-8058-adef47617cdf    33  Female        Mexico
275   d3fdd03d-cb34-4127-a0e9-cb923101283d    25   Other   Switzerland
276   886b9aca-5d31-4065-a308-ddf1140fe728    21    Male       Denmark
277   0d15b643-977d-4ec4-9599-7c59b5ee3e73  <NA>  Female        Mexico
278   a730f213-444f-460d-b28d-8ce751973bd9    49    Male        Turkey
279   a61e91e8-43a9-40b9-964e-c354110f0e43    29   Other       Denmark

### After validating missing values, duplicate records, data types and consistency rules, no issues were found that could materially affect the analysis. The dataset is considered reliable for the subsequent exploratory analyses.